# Generated by Django 2.2.5 on 2021-10-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultclassicsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultclassics',
            name='type',
            field=models.CharField(choices=[('Genres', 'Genres'), ('Year', 'Year'), ('Director', 'Director'), ('Color', 'Color')], max_length=25),
        ),
    ]
