# Generated by Django 2.2.5 on 2022-03-02 16:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turtles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('species', models.CharField(choices=[('Turtle', 'Turtle'), ('Tortoise', 'Tortoise'), ('Terrapin', 'Terrapin')], max_length=15)),
                ('description', models.TextField(max_length=150)),
                ('rescue_cost', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('locality', models.CharField(choices=[('Americas', 'Americas'), ('Europe', 'Europe'), ('Asia', 'Asia')], max_length=15)),
            ],
            managers=[
                ('Turtles', django.db.models.manager.Manager()),
            ],
        ),
    ]
