# Generated by Django 2.2.5 on 2022-04-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_name', models.CharField(max_length=60)),
                ('trail_nearest_city', models.CharField(blank=True, max_length=60)),
                ('trail_state', models.CharField(choices=[('CA', 'California'), ('IA', 'Iowa'), ('WV', 'West Virginia'), ('OR', 'Oregon'), ('IN', 'Indiana'), ('HI', 'Hawaii'), ('TX', 'Texas'), ('NE', 'Nebraska'), ('NC', 'North Carolina'), ('ME', 'Maine'), ('IL', 'Illinois'), ('SC', 'South Carolina'), ('AK', 'Alaska'), ('GA', 'Georgia'), ('NJ', 'New Jersey'), ('NH', 'New Hampshire'), ('PA', 'Pennsylvania'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('MI', 'Michigan'), ('WY', 'Wyoming'), ('DE', 'Delaware'), ('VT', 'Vermont'), ('CT', 'Connecticut'), ('MA', 'Massachusetts'), ('TN', 'Tennessee'), ('ID', 'Idaho'), ('FL', 'Florida'), ('MS', 'Mississippi'), ('KS', 'Kansas'), ('MD', 'Maryland'), ('OK', 'Oklahoma'), ('MO', 'Missouri'), ('AR', 'Arkansas'), ('CO', 'Colorado'), ('AZ', 'Arizona'), ('RI', 'Rhode Island'), ('UT', 'Utah'), ('NY', 'New York'), ('MT', 'Montana'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('NV', 'Nevada'), ('VA', 'Virginia'), ('MN', 'Minnesota'), ('WI', 'Wisconsin'), ('SD', 'South Dakota'), ('AL', 'Alabama'), ('WA', 'Washington'), ('NM', 'New Mexico')], max_length=60)),
                ('trail_directions', models.TextField(blank=True, default='How do we get there?')),
                ('trail_need_to_know', models.TextField(blank=True, default='Sketchy sections, flooded areas. Whateverfellow bikers need to know.')),
                ('trail_review', models.TextField(default='How was it?')),
                ('trail_difficulty', models.CharField(choices=[('6', '6 - Very Difficult'), ('5', '5 - Difficult'), ('1', '1 - Easy'), ('4', '4 - Intermediate/Difficult'), ('3', '3 - Intermediate')], max_length=60)),
            ],
        ),
    ]
