# Generated by Django 2.2.5 on 2022-04-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTB_Trails', '0002_auto_20220406_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtrail',
            name='difficulty',
            field=models.CharField(choices=[('1 - Easy', '1 - Easy'), ('2 - Easy/Intermediate', '2 - Easy/Intermediate'), ('3 - Intermediate', '3 - Intermediate'), ('4 - Intermediate/Difficult', '4 - Intermediate/Difficult'), ('5 - Difficult', '5 - Difficult'), ('6 - Very Difficult', '6 - Very Difficult')], max_length=60),
        ),
        migrations.AlterField(
            model_name='reviewtrail',
            name='difficulty',
            field=models.CharField(choices=[('1 - Easy', '1 - Easy'), ('2 - Easy/Intermediate', '2 - Easy/Intermediate'), ('3 - Intermediate', '3 - Intermediate'), ('4 - Intermediate/Difficult', '4 - Intermediate/Difficult'), ('5 - Difficult', '5 - Difficult'), ('6 - Very Difficult', '6 - Very Difficult')], max_length=60),
        ),
    ]
