# Generated by Django 2.2.5 on 2022-04-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTB_Trails', '0003_auto_20220407_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtrail',
            name='difficulty',
            field=models.CharField(choices=[('Easy', '1 - Easy'), ('Easy/Intermediate', '2 - Easy/Intermediate'), ('Intermediate', '3 - Intermediate'), ('Intermediate/Difficult', '4 - Intermediate/Difficult'), ('Difficult', '5 - Difficult'), ('Very Difficult', '6 - Very Difficult')], max_length=60),
        ),
        migrations.AlterField(
            model_name='reviewtrail',
            name='difficulty',
            field=models.CharField(choices=[('Easy', '1 - Easy'), ('Easy/Intermediate', '2 - Easy/Intermediate'), ('Intermediate', '3 - Intermediate'), ('Intermediate/Difficult', '4 - Intermediate/Difficult'), ('Difficult', '5 - Difficult'), ('Very Difficult', '6 - Very Difficult')], max_length=60),
        ),
    ]
