# Generated by Django 2.2.5 on 2022-04-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTB_Trails', '0004_auto_20220407_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtrail',
            name='date_ridden',
            field=models.DateField(default='Select Date'),
        ),
    ]
