# Generated by Django 2.2.5 on 2022-04-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTB_Trails', '0005_reviewtrail_date_ridden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtrail',
            name='date_ridden',
            field=models.DateField(default='MM-DD-YYYY'),
        ),
    ]
