# Generated by Django 2.2.5 on 2022-04-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTB_Trails', '0008_auto_20220407_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtrail',
            name='date_ridden',
            field=models.DateField(),
        ),
    ]
