# Generated by Django 2.2.5 on 2022-04-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTB_Trails', '0009_auto_20220407_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtrail',
            name='date_ridden',
            field=models.DateField(blank=True),
        ),
    ]
