# Generated by Django 2.2.5 on 2022-04-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MTB_Trails', '0010_auto_20220407_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewtrail',
            name='date_ridden',
        ),
    ]
