# Generated by Django 2.2.5 on 2022-04-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MTB_Trails', '0011_remove_reviewtrail_date_ridden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateTrail',
        ),
    ]
