# Generated by Django 2.2.5 on 2022-07-04 17:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Please enter your full name', max_length=60)),
                ('Topic', models.CharField(choices=[('Professional Inquiry', 'Professional Inquiry'), ('Questions', 'Questions'), ('Collaboration', 'Collaboration'), ('Other', 'Other')], default='Professional Inquiry', max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.CharField(default="Anything else you'd like to say?", max_length=500)),
            ],
            managers=[
                ('ContactForm', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.CharField(max_length=15)),
                ('Condition', models.CharField(max_length=30)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('City', models.CharField(max_length=30)),
            ],
            managers=[
                ('WeatherInfo', django.db.models.manager.Manager()),
            ],
        ),
    ]
