# Generated by Django 2.2.5 on 2022-01-11 20:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=75)),
                ('cuisine', models.CharField(choices=[('Italian', 'Italian'), ('American', 'American'), ('Asian Fusion', 'Asian Fusion'), ('Bar', 'Bar'), ('BBQ', 'BBQ'), ('French', 'French'), ('Greek', 'Greek'), ('Mediterranean', 'Mediterranean'), ('Mexican', 'Mexican'), ('Pizza', 'Pizza'), ('Seafood', 'Seafood'), ('Southern Food', 'Southern Food'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese')], max_length=100)),
                ('borough', models.CharField(choices=[('Manhattan', 'Manhattan'), ('Brooklyn', 'Brooklyn'), ('Queens', 'Queens'), ('Staten Island', 'Staten Island'), ('Bronx', 'Bronx')], max_length=100)),
                ('neighborhood', models.CharField(max_length=75)),
                ('price_range', models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$'), ('$$$$', '$$$$')], max_length=100)),
                ('address', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
            ],
            managers=[
                ('Restaurants', django.db.models.manager.Manager()),
            ],
        ),
    ]
