# Generated by Django 2.2.5 on 2022-01-06 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NYC_Guide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='rest_name',
            new_name='restaurant_name',
        ),
    ]
