# Generated by Django 2.2.5 on 2022-01-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYC_Guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
