# Generated by Django 2.2.5 on 2022-01-10 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NYC_Guide', '0002_auto_20220109_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='slug',
        ),
    ]
