# Generated by Django 2.2.5 on 2021-11-01 17:21

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyFB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('Players', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='reason',
            field=models.TextField(default='', max_length=500),
        ),
    ]
