# Generated by Django 2.2.5 on 2021-10-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyFB', '0002_auto_20211021_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='reason',
            field=models.TextField(default='Why would this hero be good at this position?', max_length=100),
        ),
    ]
