# Generated by Django 2.2.5 on 2021-10-29 20:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyFB', '0005_auto_20211021_2134'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('Players', django.db.models.manager.Manager()),
            ],
        ),
    ]
