# Generated by Django 2.2.5 on 2022-06-20 17:34

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('Entries', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherMoment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('WeatherMoments', django.db.models.manager.Manager()),
            ],
        ),
    ]
