# Generated by Django 2.2.5 on 2022-01-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestCities', '0003_auto_20220113_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='cost_of_living_average',
            field=models.CharField(choices=[('Average', 'Average'), ('Below Average', 'Below Average'), ('Above Average', 'Above Average')], max_length=60),
        ),
    ]
