# Generated by Django 2.2.5 on 2022-01-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestCities', '0036_auto_20220115_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='cost_of_living_average',
            field=models.CharField(choices=[('Below Average', 'Below Average'), ('Average', 'Average'), ('Above Average', 'Above Average')], max_length=60),
        ),
    ]
