# Generated by Django 2.2.5 on 2022-07-04 17:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=30)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(default='', max_length=50)),
            ],
            managers=[
                ('Accounts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security', models.CharField(choices=[('IP', 'IP'), ('GPKG', 'GPKG'), ('NVDA', 'NVDA'), ('KO', 'KO')], default='', max_length=7)),
                ('documents', models.CharField(choices=[('BalanceSheet', 'BalanceSheet'), ('IncomeStatement', 'IncomeStatement'), ('Earnings', 'Earnings'), ('Chart', 'Chart'), ('PriceRating', 'PriceRating')], max_length=30)),
            ],
            managers=[
                ('Approaches', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='AAPL', max_length=4)),
                ('style', models.CharField(choices=[('Appreciation', 'Appreciation'), ('Consistent Growth', 'Consistent Growth'), ('Dividends', 'Dividends'), ('Options', 'Options')], default='', max_length=30)),
                ('documents_set_1', models.CharField(choices=[('BalanceSheet', 'BalanceSheet'), ('IncomeStatement', 'IncomeStatement'), ('Earnings', 'Earnings'), ('Chart', 'Chart'), ('PriceRating', 'PriceRating')], default='BalanceSheet', max_length=30)),
                ('documents_set_2', models.CharField(choices=[('BalanceSheet', 'BalanceSheet'), ('IncomeStatement', 'IncomeStatement'), ('Earnings', 'Earnings'), ('Chart', 'Chart'), ('PriceRating', 'PriceRating')], default='IncomeStatement', max_length=30)),
                ('documents_set_3', models.CharField(choices=[('BalanceSheet', 'BalanceSheet'), ('IncomeStatement', 'IncomeStatement'), ('Earnings', 'Earnings'), ('Chart', 'Chart'), ('PriceRating', 'PriceRating')], default='Earnings', max_length=30)),
            ],
            managers=[
                ('Evaluations', django.db.models.manager.Manager()),
            ],
        ),
    ]
