# Generated by Django 2.2.5 on 2022-07-30 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='destination',
            managers=[
            ],
        ),
    ]
