# Generated by Django 2.2.5 on 2021-11-05 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_player', models.CharField(default='', max_length=60)),
                ('sr_time', models.CharField(default='', max_length=30)),
                ('sr_platform', models.CharField(choices=[('Wii U', 'Wii U'), ('PlayStation 4', 'PlayStation 4'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Xbox One', 'Xbox One'), ('PlayStation', 'PlayStation'), ('Xbox', 'Xbox'), ('Atari 2600', 'Atari 2600'), ('Wii', 'Wii'), ('NES', 'NES'), ('Switch', 'Switch'), ('PlayStation 3', 'PlayStation 3'), ('Nintendo DS', 'Nintendo DS'), ('Sega Genesis', 'Sega Genesis'), ('PC', 'PC'), ('PSP', 'PSP'), ('Xbox 360', 'Xbox 360'), ('PlayStation 2', 'PlayStation 2'), ('N64', 'N64'), ('Xbox Series X', 'Xbox Series X'), ('SNES', 'SNES'), ('Game Boy Advance', 'Game Boy Advance'), ('GameCube', 'GameCube'), ('Game Boy', 'Game Boy'), ('PlayStation 5', 'PlayStation 5')], max_length=60)),
                ('sr_date', models.DateField()),
                ('sr_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpeedRun.GameName')),
            ],
        ),
    ]
