# Generated by Django 2.2.5 on 2021-12-08 23:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(default='', max_length=60)),
                ('time', models.CharField(default='HH:MM:SS', max_length=30)),
                ('platform', models.CharField(choices=[('Atari 2600', 'Atari 2600'), ('Xbox', 'Xbox'), ('Xbox 360', 'Xbox 360'), ('Xbox One', 'Xbox One'), ('Xbox Series X', 'Xbox Series X'), ('NES', 'NES'), ('Game Boy', 'Game Boy'), ('SNES', 'SNES'), ('N64', 'N64'), ('Game Boy Advance', 'Game Boy Advance'), ('GameCube', 'GameCube'), ('Nintendo DS', 'Nintendo DS'), ('Wii', 'Wii'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Wii U', 'Wii U'), ('Switch', 'Switch'), ('Sega Genesis', 'Sega Genesis'), ('PlayStation', 'PlayStation'), ('PlayStation 2', 'PlayStation 2'), ('PSP', 'PSP'), ('PlayStation 3', 'PlayStation 3'), ('PlayStation 4', 'PlayStation 4'), ('PlayStation 5', 'PlayStation 5'), ('PC', 'PC')], default='', max_length=60)),
                ('date', models.DateField(default=datetime.date.today)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='SpeedRun.GameName')),
            ],
        ),
    ]
