# Generated by Django 2.2.5 on 2021-11-11 00:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(default='', max_length=60)),
                ('time', models.CharField(default='', max_length=30)),
                ('platform', models.CharField(choices=[('Nintendo 3DS', 'Nintendo 3DS'), ('Sega Genesis', 'Sega Genesis'), ('N64', 'N64'), ('Xbox 360', 'Xbox 360'), ('GameCube', 'GameCube'), ('NES', 'NES'), ('PlayStation 3', 'PlayStation 3'), ('Xbox One', 'Xbox One'), ('PC', 'PC'), ('Nintendo DS', 'Nintendo DS'), ('Xbox', 'Xbox'), ('Game Boy Advance', 'Game Boy Advance'), ('Switch', 'Switch'), ('Atari 2600', 'Atari 2600'), ('SNES', 'SNES'), ('PlayStation 5', 'PlayStation 5'), ('Wii U', 'Wii U'), ('PSP', 'PSP'), ('PlayStation 4', 'PlayStation 4'), ('PlayStation', 'PlayStation'), ('Wii', 'Wii'), ('Game Boy', 'Game Boy'), ('Xbox Series X', 'Xbox Series X'), ('PlayStation 2', 'PlayStation 2')], default='', max_length=60)),
                ('date', models.DateField(default=datetime.date.today)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpeedRun.GameName')),
            ],
        ),
    ]
