# Generated by Django 2.2.5 on 2021-11-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedRun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='sr_platform',
            field=models.CharField(choices=[('Xbox One', 'Xbox One'), ('Xbox Series X', 'Xbox Series X'), ('SNES', 'SNES'), ('PC', 'PC'), ('PlayStation 4', 'PlayStation 4'), ('Nintendo 3DS', 'Nintendo 3DS'), ('N64', 'N64'), ('PlayStation 5', 'PlayStation 5'), ('Game Boy Advance', 'Game Boy Advance'), ('Nintendo DS', 'Nintendo DS'), ('Game Boy', 'Game Boy'), ('PSP', 'PSP'), ('PlayStation 3', 'PlayStation 3'), ('GameCube', 'GameCube'), ('Sega Genesis', 'Sega Genesis'), ('PlayStation', 'PlayStation'), ('Wii', 'Wii'), ('Switch', 'Switch'), ('Xbox 360', 'Xbox 360'), ('Xbox', 'Xbox'), ('Wii U', 'Wii U'), ('PlayStation 2', 'PlayStation 2'), ('NES', 'NES'), ('Atari 2600', 'Atari 2600')], max_length=60),
        ),
    ]
