# Generated by Django 2.2.5 on 2021-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedRun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='platform',
            field=models.CharField(choices=[('Atari 2600', 'Atari 2600'), ('Xbox', 'Xbox'), ('Xbox 360', 'Xbox 360'), ('Xbox One', 'Xbox One'), ('Xbox Series X', 'Xbox Series X'), ('NES', 'NES'), ('Game Boy', 'Game Boy'), ('SNES', 'SNES'), ('N64', 'N64'), ('Game Boy Advance', 'Game Boy Advance'), ('GameCube', 'GameCube'), ('Nintendo DS', 'Nintendo DS'), ('Wii', 'Wii'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Wii U', 'Wii U'), ('Switch', 'Switch'), ('Sega Genesis', 'Sega Genesis'), ('PlayStation', 'PlayStation'), ('PlayStation 2', 'PlayStation 2'), ('PSP', 'PSP'), ('PlayStation 3', 'PlayStation 3'), ('PlayStation 4', 'PlayStation 4'), ('PlayStation 5', 'PlayStation 5'), ('PC', 'PC')], default='', max_length=60),
        ),
    ]
