# Generated by Django 2.2.5 on 2021-11-05 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedRun', '0002_auto_20211105_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='sr_game',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='sr_player',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='sr_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='record',
            name='sr_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='sr_platform',
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='record',
            name='platform',
            field=models.CharField(choices=[('Nintendo 3DS', 'Nintendo 3DS'), ('Atari 2600', 'Atari 2600'), ('PlayStation', 'PlayStation'), ('PC', 'PC'), ('Xbox', 'Xbox'), ('Wii', 'Wii'), ('PSP', 'PSP'), ('GameCube', 'GameCube'), ('NES', 'NES'), ('PlayStation 4', 'PlayStation 4'), ('Xbox 360', 'Xbox 360'), ('Game Boy Advance', 'Game Boy Advance'), ('Nintendo DS', 'Nintendo DS'), ('SNES', 'SNES'), ('Game Boy', 'Game Boy'), ('Sega Genesis', 'Sega Genesis'), ('PlayStation 3', 'PlayStation 3'), ('Xbox One', 'Xbox One'), ('Wii U', 'Wii U'), ('PlayStation 5', 'PlayStation 5'), ('N64', 'N64'), ('PlayStation 2', 'PlayStation 2'), ('Xbox Series X', 'Xbox Series X'), ('Switch', 'Switch')], default='', max_length=60),
        ),
    ]
