# Generated by Django 2.2.5 on 2021-11-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedRun', '0003_auto_20211105_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='platform',
            field=models.CharField(choices=[('Xbox', 'Xbox'), ('PlayStation 3', 'PlayStation 3'), ('PC', 'PC'), ('Xbox Series X', 'Xbox Series X'), ('Atari 2600', 'Atari 2600'), ('N64', 'N64'), ('NES', 'NES'), ('Xbox 360', 'Xbox 360'), ('Sega Genesis', 'Sega Genesis'), ('PlayStation 5', 'PlayStation 5'), ('PlayStation 2', 'PlayStation 2'), ('Wii', 'Wii'), ('PSP', 'PSP'), ('PlayStation', 'PlayStation'), ('PlayStation 4', 'PlayStation 4'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Xbox One', 'Xbox One'), ('SNES', 'SNES'), ('Game Boy', 'Game Boy'), ('GameCube', 'GameCube'), ('Nintendo DS', 'Nintendo DS'), ('Game Boy Advance', 'Game Boy Advance'), ('Switch', 'Switch'), ('Wii U', 'Wii U')], default='', max_length=60),
        ),
    ]
