# Generated by Django 2.2.5 on 2022-03-02 16:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Classical', 'Classical'), ('Romantic', 'Romantic'), ('Baroque', 'Baroque'), ('20th Century', '20th Century')], max_length=15)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('death_year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('nationality', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
            managers=[
                ('Composers', django.db.models.manager.Manager()),
            ],
        ),
    ]
