# Generated by Django 2.2.5 on 2022-05-17 17:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('hometown', models.CharField(max_length=50)),
            ],
            managers=[
                ('Entry', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherMoment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('WeatherMoments', django.db.models.manager.Manager()),
            ],
        ),
    ]
