# Generated by Django 2.2.5 on 2022-06-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
