# Generated by Django 2.2.5 on 2022-01-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(blank=True, default='', max_length=50)),
                ('Album', models.CharField(blank=True, default='', max_length=50)),
                ('Song', models.CharField(blank=True, default='', max_length=50)),
                ('Review', models.TextField(blank=True, default='', max_length=300)),
                ('Stars', models.CharField(choices=[('1 star', '1 star'), ('2 star', '2 star'), ('3 star', '3 star'), ('4 star', '4 star'), ('5 star', '5 star')], max_length=10)),
            ],
        ),
    ]
