# Generated by Django 2.2.5 on 2022-01-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Stars',
            field=models.CharField(choices=[('3 star', '3 star'), ('5 star', '5 star'), ('4 star', '4 star'), ('2 star', '2 star'), ('1 star', '1 star')], max_length=10),
        ),
    ]
