# Generated by Django 2.2.5 on 2022-01-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReviews', '0002_auto_20220105_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Stars',
            field=models.CharField(choices=[('5 star', '5 star'), ('2 star', '2 star'), ('4 star', '4 star'), ('3 star', '3 star'), ('1 star', '1 star')], max_length=10),
        ),
    ]
