# Generated by Django 2.2.5 on 2022-01-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReviews', '0003_auto_20220106_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Stars',
            field=models.CharField(choices=[('1 star', '1 star'), ('5 star', '5 star'), ('3 star', '3 star'), ('2 star', '2 star'), ('4 star', '4 star')], max_length=10),
        ),
    ]
