# Generated by Django 2.2.5 on 2021-12-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Namerec', models.CharField(blank=True, default='', max_length=50)),
                ('Address', models.CharField(blank=True, default='', max_length=100)),
                ('Service_Product', models.CharField(blank=True, default='What Service or Product is being done?...', max_length=100)),
                ('Description', models.TextField(blank=True, default='Job Description...', max_length=500)),
                ('Details', models.CharField(blank=True, default='Add Details...', max_length=200)),
                ('Est_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000000)),
            ],
        ),
    ]
