# Generated by Django 2.2.5 on 2022-03-05 22:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('release_date', models.CharField(max_length=50)),
            ],
            managers=[
                ('Favorites', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            managers=[
                ('Publisher', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2025)])),
                ('rating', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('genre', models.CharField(choices=[('action', 'action'), ('racing', 'racing'), ('horror', 'horror'), ('adventure', 'adventure'), ('RPG', 'RPG'), ('RTS', 'RTS')], default=('action', 'action'), max_length=50)),
                ('publisher_name', models.CharField(max_length=50)),
                ('review', models.TextField(blank=True, default='', max_length=500)),
                ('publisher', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='GameStats.Publishers')),
            ],
            managers=[
                ('Game', django.db.models.manager.Manager()),
            ],
        ),
    ]
