# Generated by Django 2.2.5 on 2021-12-16 17:49

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Purple', 'Purple')], default='', max_length=30)),
                ('PersonCount', models.IntegerField()),
                ('Price', models.FloatField(max_length=30)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
