# Generated by Django 2.2.5 on 2021-10-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InlineSpeedSkates', '0002_review_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
