# Generated by Django 2.2.5 on 2021-06-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SciFiWatchlist', '0002_auto_20210612_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ReleaseYear',
            field=models.IntegerField(blank=True),
        ),
    ]
