# Generated by Django 2.2.5 on 2021-06-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SciFiWatchlist', '0003_auto_20210612_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Film',
        ),
    ]
