# Generated by Django 2.2.5 on 2021-06-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SciFiWatchlist', '0004_auto_20210612_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='DirectorName',
        ),
        migrations.RemoveField(
            model_name='film',
            name='FilmName',
        ),
        migrations.RemoveField(
            model_name='film',
            name='ReleaseYear',
        ),
        migrations.RemoveField(
            model_name='film',
            name='StarNames',
        ),
        migrations.AddField(
            model_name='film',
            name='Director_names',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='Film_star_names',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='Name_of_film',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='Year_of_film',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
