# Generated by Django 2.2.5 on 2021-08-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGames', '0003_merge_20210830_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ('-Favorite', 'Name', 'id')},
        ),
    ]
