# Generated by Django 2.2.5 on 2022-07-26 01:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('breed', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=30)),
                ('coat', models.CharField(max_length=30)),
                ('size', models.CharField(choices=[('X-small', 'Xtra-Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('X-large', 'Xtra-Large')], max_length=20)),
            ],
            managers=[
                ('Dog', django.db.models.manager.Manager()),
            ],
        ),
    ]
