# Generated by Django 2.2.5 on 2022-04-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroAbility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='threat_Level',
            field=models.CharField(choices=[('Nonexistent', 'Nonexistent'), ('Mild Inconvenience', 'Mild Inconvenience'), ('Minor Threat', 'Minor Threat'), ('Robin Equivalent', 'Robin Equivalent'), ('Major Threat', 'Major Threat'), ('World Ending', 'World Ending')], default='', max_length=20),
        ),
    ]
