# Generated by Django 2.2.5 on 2021-08-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGames', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardGame',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
