# Generated by Django 2.2.5 on 2021-08-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGames', '0002_auto_20210825_1709'),
        ('BoardGames', '0002_auto_20210821_2357'),
    ]

    operations = [
    ]
