# Generated by Django 2.2.5 on 2021-08-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BoardGames', '0002_auto_20210811_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Publisher', models.CharField(max_length=50)),
                ('Year', models.IntegerField(default=2021)),
                ('Description', models.TextField(default='Type your review here (optional)')),
                ('Thumbnail', models.CharField(blank=True, max_length=100)),
                ('Image', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
