# Generated by Django 2.2.5 on 2021-07-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_Maker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_instructions', models.TextField(default='Please write your instructions here')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_type', models.CharField(choices=[('Appetizers', 'Appetizers'), ('Drinks', 'Drinks'), ('Snacks', 'Snacks'), ('Entrees', 'Entrees')], max_length=60)),
                ('recipe_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipe_Maker.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='recipe_ingredients',
            field=models.TextField(default="Please write you're ingredients and amounts"),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='RecipeName',
        ),
        migrations.AddField(
            model_name='instructions',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipe_Maker.Recipe'),
        ),
    ]
