# Generated by Django 2.2.5 on 2021-11-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeReviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='review',
            field=models.TextField(max_length=1500),
        ),
    ]
