# Generated by Django 2.2.5 on 2022-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATVTrails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atvtrails',
            name='trail_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
