# Generated by Django 2.2.5 on 2021-07-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonName', models.CharField(blank=True, default='', max_length=120, verbose_name='Common Name')),
                ('latinName', models.CharField(blank=True, default='', max_length=120, verbose_name='Latin Name')),
                ('location', models.CharField(choices=[('Africa', 'Africa'), ('The Arctics', 'The Arctics'), ('Asia', 'Asia'), ('Australia', 'Australia'), ('Europe', 'Europe'), ('Education', 'Education'), ('North America', 'North America'), ('South America', 'South America'), ('World Oceans', 'World Oceans')], max_length=60)),
                ('SSP', models.CharField(choices=[(True, 'Yes'), (False, 'No')], max_length=60)),
            ],
        ),
    ]
