# Generated by Django 2.2.5 on 2021-07-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZooAnimals', '0002_auto_20210706_1757'),
        ('ZooAnimals', '0002_auto_20210706_1834'),
    ]

    operations = [
    ]
