# Generated by Django 2.2.5 on 2021-07-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeighborhoodReview', '0002_auto_20210729_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(choices=[('Northwest', 'Northwest'), ('Southwest', 'Southwest'), ('Northeast', 'Northeast'), ('Beaverton', 'Beaverton'), ('Southeast', 'Southeast'), ('Hillsboro', 'Hillsboro'), ('North', 'North')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='walkability',
            field=models.CharField(choices=[('Somewhat Walkable', 'Somewhat Walkable'), ('Very Walkable', 'Very Walkable'), ('Not Walkable', 'Not Walkable')], max_length=40),
        ),
    ]
