# Generated by Django 2.2.5 on 2021-07-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeighborhoodReview', '0003_auto_20210729_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(choices=[('Northwest', 'Northwest'), ('Beaverton', 'Beaverton'), ('Southeast', 'Southeast'), ('Southwest', 'Southwest'), ('Hillsboro', 'Hillsboro'), ('North', 'North'), ('Northeast', 'Northeast')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='commute',
            field=models.CharField(choices=[('Fair', 'Fair'), ('Short', 'Short'), ('Long', 'Long')], max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_life_stage',
            field=models.CharField(choices=[('Family', 'Family'), ('Retiree', 'Retiree'), ('Young Professional', 'Young Professional')], max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='walkability',
            field=models.CharField(choices=[('Very Walkable', 'Very Walkable'), ('Somewhat Walkable', 'Somewhat Walkable'), ('Not Walkable', 'Not Walkable')], max_length=40),
        ),
    ]
