# Generated by Django 2.2.5 on 2021-07-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeighborhoodReview', '0004_auto_20210730_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(choices=[('Northeast', 'Northeast'), ('Hillsboro', 'Hillsboro'), ('Northwest', 'Northwest'), ('Beaverton', 'Beaverton'), ('Southeast', 'Southeast'), ('Southwest', 'Southwest'), ('North', 'North')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='commute',
            field=models.CharField(choices=[('Short', 'Short'), ('Fair', 'Fair'), ('Long', 'Long')], max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_life_stage',
            field=models.CharField(choices=[('Family', 'Family'), ('Young Professional', 'Young Professional'), ('Retiree', 'Retiree')], max_length=40),
        ),
    ]
