# Generated by Django 2.2.5 on 2021-07-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeighborhoodReview', '0005_auto_20210730_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(choices=[('Southeast', 'Southeast'), ('Hillsboro', 'Hillsboro'), ('Northeast', 'Northeast'), ('Beaverton', 'Beaverton'), ('Southwest', 'Southwest'), ('Northwest', 'Northwest'), ('North', 'North')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='commute',
            field=models.CharField(choices=[('Short', 'Short'), ('Long', 'Long'), ('Fair', 'Fair')], max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_life_stage',
            field=models.CharField(choices=[('Retiree', 'Retiree'), ('Family', 'Family'), ('Young Professional', 'Young Professional')], max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='walkability',
            field=models.CharField(choices=[('Not Walkable', 'Not Walkable'), ('Somewhat Walkable', 'Somewhat Walkable'), ('Very Walkable', 'Very Walkable')], max_length=40),
        ),
    ]
