# Generated by Django 2.2.5 on 2021-07-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeighborhoodReview', '0006_auto_20210730_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(choices=[('Hillsboro', 'Hillsboro'), ('Southeast', 'Southeast'), ('Southwest', 'Southwest'), ('North', 'North'), ('Northeast', 'Northeast'), ('Northwest', 'Northwest'), ('Beaverton', 'Beaverton')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_life_stage',
            field=models.CharField(choices=[('Family', 'Family'), ('Retiree', 'Retiree'), ('Young Professional', 'Young Professional')], max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='walkability',
            field=models.CharField(choices=[('Very Walkable', 'Very Walkable'), ('Somewhat Walkable', 'Somewhat Walkable'), ('Not Walkable', 'Not Walkable')], max_length=40),
        ),
    ]
