# Generated by Django 2.2.5 on 2022-07-26 01:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, unique=True)),
                ('type', models.CharField(choices=[('TV Series', 'TV Series'), ('ONA', 'ONA'), ('Movie', 'Movie'), ('OVA', 'OVA'), ('Other', 'Other')], default='', max_length=60)),
                ('genre', models.CharField(choices=[('Action / Adventure', 'Action / Adventure'), ('Comedy', 'Comedy'), ('Sports', 'Sports'), ('Fantasy / Sci-Fi / Supernatural', 'Fantasy / Sci-Fi / Supernatural'), ('Romance / Slice of Life', 'Romance / Slice of Life'), ('Horror / Suspense', 'Horror / Suspense'), ('Drama / Mystery', 'Drama / Mystery')], default='', max_length=60)),
                ('rating', models.CharField(choices=[('2', '2'), ('5', '5'), ('0', '0'), ('3', '3'), ('1', '1'), ('4', '4')], default='', help_text='5 = Highest', max_length=1)),
                ('review', models.CharField(blank=True, default='', max_length=500)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
            ],
            managers=[
                ('animes', django.db.models.manager.Manager()),
            ],
        ),
    ]
