# Generated by Django 2.2.5 on 2022-06-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ani',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Sports', 'Sports'), ('Drama / Mystery', 'Drama / Mystery'), ('Romance / Slice of Life', 'Romance / Slice of Life'), ('Action / Adventure', 'Action / Adventure'), ('Horror / Suspense', 'Horror / Suspense'), ('Fantasy / Sci-Fi / Supernatural', 'Fantasy / Sci-Fi / Supernatural')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='ani',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('4', '4'), ('5', '5'), ('0', '0'), ('2', '2')], default='', help_text='5 = Highest', max_length=1),
        ),
        migrations.AlterField(
            model_name='ani',
            name='type',
            field=models.CharField(choices=[('Other', 'Other'), ('OVA', 'OVA'), ('ONA', 'ONA'), ('Movie', 'Movie'), ('TV Series', 'TV Series')], default='', max_length=60),
        ),
    ]
