# Generated by Django 2.2.5 on 2022-05-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ani',
            name='genre',
            field=models.CharField(choices=[('Fantasy / Sci-Fi / Supernatural', 'Fantasy / Sci-Fi / Supernatural'), ('Horror / Suspense', 'Horror / Suspense'), ('Comedy', 'Comedy'), ('Sports', 'Sports'), ('Action / Adventure', 'Action / Adventure'), ('Drama / Mystery', 'Drama / Mystery'), ('Romance / Slice of Life', 'Romance / Slice of Life')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='ani',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('5', '5'), ('2', '2'), ('0', '0'), ('4', '4'), ('3', '3')], default='', help_text='5 = Highest', max_length=1),
        ),
        migrations.AlterField(
            model_name='ani',
            name='type',
            field=models.CharField(choices=[('ONA', 'ONA'), ('Movie', 'Movie'), ('Other', 'Other'), ('TV Series', 'TV Series'), ('OVA', 'OVA')], default='', max_length=60),
        ),
    ]
