# Generated by Django 2.2.5 on 2021-06-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Crypto', 'Crypto'), ('Fuse', 'Fuse'), ('Octane', 'Octane'), ('Rampart', 'Rampart'), ('Bangalore', 'Bangalore'), ('Revenant', 'Revenant'), ('Caustic', 'Caustic'), ('Lifeline', 'Lifeline'), ('Mirage', 'Mirage'), ('Bloodhound', 'Bloodhound'), ('Horizon', 'Horizon'), ('Loba', 'Loba'), ('Valkyrie', 'Valkyrie'), ('Wraith', 'Wraith'), ('Wattson', 'Wattson'), ('Gibraltar', 'Gibraltar'), ('Pathfinder', 'Pathfinder')], max_length=60),
        ),
    ]
