# Generated by Django 2.2.5 on 2021-06-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0002_auto_20210623_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Pathfinder', 'Pathfinder'), ('Fuse', 'Fuse'), ('Mirage', 'Mirage'), ('Wattson', 'Wattson'), ('Caustic', 'Caustic'), ('Crypto', 'Crypto'), ('Gibraltar', 'Gibraltar'), ('Bangalore', 'Bangalore'), ('Revenant', 'Revenant'), ('Octane', 'Octane'), ('Loba', 'Loba'), ('Valkyrie', 'Valkyrie'), ('Rampart', 'Rampart'), ('Wraith', 'Wraith'), ('Lifeline', 'Lifeline'), ('Horizon', 'Horizon'), ('Bloodhound', 'Bloodhound')], max_length=60),
        ),
    ]
