# Generated by Django 2.2.5 on 2021-06-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0003_auto_20210623_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Mirage', 'Mirage'), ('Rampart', 'Rampart'), ('Bloodhound', 'Bloodhound'), ('Valkyrie', 'Valkyrie'), ('Pathfinder', 'Pathfinder'), ('Gibraltar', 'Gibraltar'), ('Lifeline', 'Lifeline'), ('Fuse', 'Fuse'), ('Revenant', 'Revenant'), ('Loba', 'Loba'), ('Wraith', 'Wraith'), ('Bangalore', 'Bangalore'), ('Wattson', 'Wattson'), ('Horizon', 'Horizon'), ('Octane', 'Octane'), ('Caustic', 'Caustic'), ('Crypto', 'Crypto')], max_length=60),
        ),
    ]
