# Generated by Django 2.2.5 on 2021-06-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0004_auto_20210623_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Wattson', 'Wattson'), ('Octane', 'Octane'), ('Bangalore', 'Bangalore'), ('Fuse', 'Fuse'), ('Horizon', 'Horizon'), ('Caustic', 'Caustic'), ('Pathfinder', 'Pathfinder'), ('Lifeline', 'Lifeline'), ('Bloodhound', 'Bloodhound'), ('Crypto', 'Crypto'), ('Rampart', 'Rampart'), ('Wraith', 'Wraith'), ('Mirage', 'Mirage'), ('Revenant', 'Revenant'), ('Loba', 'Loba'), ('Valkyrie', 'Valkyrie'), ('Gibraltar', 'Gibraltar')], max_length=60),
        ),
    ]
