# Generated by Django 2.2.5 on 2021-06-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0005_auto_20210623_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Rampart', 'Rampart'), ('Wraith', 'Wraith'), ('Octane', 'Octane'), ('Caustic', 'Caustic'), ('Loba', 'Loba'), ('Wattson', 'Wattson'), ('Horizon', 'Horizon'), ('Mirage', 'Mirage'), ('Crypto', 'Crypto'), ('Revenant', 'Revenant'), ('Valkyrie', 'Valkyrie'), ('Pathfinder', 'Pathfinder'), ('Fuse', 'Fuse'), ('Lifeline', 'Lifeline'), ('Bloodhound', 'Bloodhound'), ('Bangalore', 'Bangalore'), ('Gibraltar', 'Gibraltar')], max_length=60),
        ),
    ]
