# Generated by Django 2.2.5 on 2021-06-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0006_auto_20210624_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Bloodhound', 'Bloodhound'), ('Caustic', 'Caustic'), ('Pathfinder', 'Pathfinder'), ('Lifeline', 'Lifeline'), ('Wattson', 'Wattson'), ('Valkyrie', 'Valkyrie'), ('Horizon', 'Horizon'), ('Fuse', 'Fuse'), ('Wraith', 'Wraith'), ('Revenant', 'Revenant'), ('Bangalore', 'Bangalore'), ('Rampart', 'Rampart'), ('Mirage', 'Mirage'), ('Crypto', 'Crypto'), ('Gibraltar', 'Gibraltar'), ('Loba', 'Loba'), ('Octane', 'Octane')], max_length=60),
        ),
    ]
