# Generated by Django 2.2.5 on 2021-06-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0007_auto_20210624_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Horizon', 'Horizon'), ('Octane', 'Octane'), ('Gibraltar', 'Gibraltar'), ('Rampart', 'Rampart'), ('Pathfinder', 'Pathfinder'), ('Wraith', 'Wraith'), ('Loba', 'Loba'), ('Bangalore', 'Bangalore'), ('Fuse', 'Fuse'), ('Mirage', 'Mirage'), ('Revenant', 'Revenant'), ('Bloodhound', 'Bloodhound'), ('Caustic', 'Caustic'), ('Wattson', 'Wattson'), ('Lifeline', 'Lifeline'), ('Valkyrie', 'Valkyrie'), ('Crypto', 'Crypto')], max_length=60),
        ),
    ]
