# Generated by Django 2.2.5 on 2021-06-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0008_auto_20210624_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Rampart', 'Rampart'), ('Bangalore', 'Bangalore'), ('Pathfinder', 'Pathfinder'), ('Loba', 'Loba'), ('Valkyrie', 'Valkyrie'), ('Revenant', 'Revenant'), ('Mirage', 'Mirage'), ('Wattson', 'Wattson'), ('Fuse', 'Fuse'), ('Octane', 'Octane'), ('Caustic', 'Caustic'), ('Crypto', 'Crypto'), ('Wraith', 'Wraith'), ('Gibraltar', 'Gibraltar'), ('Lifeline', 'Lifeline'), ('Bloodhound', 'Bloodhound'), ('Horizon', 'Horizon')], max_length=60),
        ),
    ]
