# Generated by Django 2.2.5 on 2021-06-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0009_auto_20210624_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Bloodhound', 'Bloodhound'), ('Octane', 'Octane'), ('Crypto', 'Crypto'), ('Horizon', 'Horizon'), ('Mirage', 'Mirage'), ('Revenant', 'Revenant'), ('Wattson', 'Wattson'), ('Loba', 'Loba'), ('Caustic', 'Caustic'), ('Fuse', 'Fuse'), ('Valkyrie', 'Valkyrie'), ('Wraith', 'Wraith'), ('Lifeline', 'Lifeline'), ('Bangalore', 'Bangalore'), ('Gibraltar', 'Gibraltar'), ('Rampart', 'Rampart'), ('Pathfinder', 'Pathfinder')], max_length=60),
        ),
    ]
