# Generated by Django 2.2.5 on 2021-06-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0010_auto_20210624_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Wattson', 'Wattson'), ('Horizon', 'Horizon'), ('Pathfinder', 'Pathfinder'), ('Bloodhound', 'Bloodhound'), ('Crypto', 'Crypto'), ('Mirage', 'Mirage'), ('Loba', 'Loba'), ('Wraith', 'Wraith'), ('Rampart', 'Rampart'), ('Gibraltar', 'Gibraltar'), ('Fuse', 'Fuse'), ('Bangalore', 'Bangalore'), ('Revenant', 'Revenant'), ('Lifeline', 'Lifeline'), ('Caustic', 'Caustic'), ('Valkyrie', 'Valkyrie'), ('Octane', 'Octane')], max_length=60),
        ),
    ]
