# Generated by Django 2.2.5 on 2021-06-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0011_auto_20210624_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='gp',
            field=models.PositiveIntegerField(default=0, verbose_name='Games Played'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='kills',
            field=models.PositiveIntegerField(default=0, verbose_name='Kills'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Mirage', 'Mirage'), ('Revenant', 'Revenant'), ('Fuse', 'Fuse'), ('Bloodhound', 'Bloodhound'), ('Rampart', 'Rampart'), ('Loba', 'Loba'), ('Octane', 'Octane'), ('Valkyrie', 'Valkyrie'), ('Pathfinder', 'Pathfinder'), ('Horizon', 'Horizon'), ('Bangalore', 'Bangalore'), ('Gibraltar', 'Gibraltar'), ('Wattson', 'Wattson'), ('Crypto', 'Crypto'), ('Lifeline', 'Lifeline'), ('Caustic', 'Caustic'), ('Wraith', 'Wraith')], max_length=60, verbose_name='Legend'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tpt3',
            field=models.PositiveIntegerField(default=0, verbose_name='Times Placed Top 3'),
        ),
    ]
