# Generated by Django 2.2.5 on 2021-06-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0012_auto_20210624_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Bangalore', 'Bangalore'), ('Wraith', 'Wraith'), ('Fuse', 'Fuse'), ('Mirage', 'Mirage'), ('Crypto', 'Crypto'), ('Rampart', 'Rampart'), ('Lifeline', 'Lifeline'), ('Horizon', 'Horizon'), ('Bloodhound', 'Bloodhound'), ('Valkyrie', 'Valkyrie'), ('Octane', 'Octane'), ('Revenant', 'Revenant'), ('Caustic', 'Caustic'), ('Wattson', 'Wattson'), ('Pathfinder', 'Pathfinder'), ('Gibraltar', 'Gibraltar'), ('Loba', 'Loba')], max_length=60, verbose_name='Legend'),
        ),
    ]
