# Generated by Django 2.2.5 on 2021-06-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0013_auto_20210624_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Rampart', 'Rampart'), ('Valkyrie', 'Valkyrie'), ('Horizon', 'Horizon'), ('Lifeline', 'Lifeline'), ('Bloodhound', 'Bloodhound'), ('Fuse', 'Fuse'), ('Octane', 'Octane'), ('Wraith', 'Wraith'), ('Wattson', 'Wattson'), ('Revenant', 'Revenant'), ('Crypto', 'Crypto'), ('Bangalore', 'Bangalore'), ('Loba', 'Loba'), ('Gibraltar', 'Gibraltar'), ('Pathfinder', 'Pathfinder'), ('Mirage', 'Mirage'), ('Caustic', 'Caustic')], max_length=60, verbose_name='Legend'),
        ),
    ]
