# Generated by Django 2.2.5 on 2021-06-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0014_auto_20210624_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Pathfinder', 'Pathfinder'), ('Bangalore', 'Bangalore'), ('Rampart', 'Rampart'), ('Lifeline', 'Lifeline'), ('Bloodhound', 'Bloodhound'), ('Revenant', 'Revenant'), ('Horizon', 'Horizon'), ('Gibraltar', 'Gibraltar'), ('Fuse', 'Fuse'), ('Octane', 'Octane'), ('Wattson', 'Wattson'), ('Caustic', 'Caustic'), ('Wraith', 'Wraith'), ('Mirage', 'Mirage'), ('Crypto', 'Crypto'), ('Loba', 'Loba'), ('Valkyrie', 'Valkyrie')], max_length=60, verbose_name='Legend'),
        ),
    ]
