# Generated by Django 2.2.5 on 2021-06-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0015_auto_20210624_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Pathfinder', 'Pathfinder'), ('Gibraltar', 'Gibraltar'), ('Horizon', 'Horizon'), ('Lifeline', 'Lifeline'), ('Loba', 'Loba'), ('Revenant', 'Revenant'), ('Mirage', 'Mirage'), ('Crypto', 'Crypto'), ('Valkyrie', 'Valkyrie'), ('Rampart', 'Rampart'), ('Caustic', 'Caustic'), ('Fuse', 'Fuse'), ('Wattson', 'Wattson'), ('Octane', 'Octane'), ('Bangalore', 'Bangalore'), ('Bloodhound', 'Bloodhound'), ('Wraith', 'Wraith')], max_length=60, verbose_name='Legend'),
        ),
    ]
