# Generated by Django 2.2.5 on 2021-06-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0016_auto_20210624_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Valkyrie', 'Valkyrie'), ('Bloodhound', 'Bloodhound'), ('Mirage', 'Mirage'), ('Caustic', 'Caustic'), ('Gibraltar', 'Gibraltar'), ('Fuse', 'Fuse'), ('Rampart', 'Rampart'), ('Bangalore', 'Bangalore'), ('Crypto', 'Crypto'), ('Loba', 'Loba'), ('Wattson', 'Wattson'), ('Wraith', 'Wraith'), ('Pathfinder', 'Pathfinder'), ('Revenant', 'Revenant'), ('Octane', 'Octane'), ('Lifeline', 'Lifeline'), ('Horizon', 'Horizon')], max_length=60, verbose_name='Legend'),
        ),
    ]
