# Generated by Django 2.2.5 on 2021-06-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0017_auto_20210624_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Caustic', 'Caustic'), ('Horizon', 'Horizon'), ('Loba', 'Loba'), ('Revenant', 'Revenant'), ('Wraith', 'Wraith'), ('Bangalore', 'Bangalore'), ('Pathfinder', 'Pathfinder'), ('Valkyrie', 'Valkyrie'), ('Lifeline', 'Lifeline'), ('Wattson', 'Wattson'), ('Fuse', 'Fuse'), ('Rampart', 'Rampart'), ('Octane', 'Octane'), ('Crypto', 'Crypto'), ('Mirage', 'Mirage'), ('Bloodhound', 'Bloodhound'), ('Gibraltar', 'Gibraltar')], max_length=60, verbose_name='Legend'),
        ),
    ]
