# Generated by Django 2.2.5 on 2021-06-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0018_auto_20210624_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Wraith', 'Wraith'), ('Pathfinder', 'Pathfinder'), ('Bloodhound', 'Bloodhound'), ('Crypto', 'Crypto'), ('Gibraltar', 'Gibraltar'), ('Bangalore', 'Bangalore'), ('Fuse', 'Fuse'), ('Lifeline', 'Lifeline'), ('Octane', 'Octane'), ('Valkyrie', 'Valkyrie'), ('Revenant', 'Revenant'), ('Mirage', 'Mirage'), ('Loba', 'Loba'), ('Horizon', 'Horizon'), ('Rampart', 'Rampart'), ('Caustic', 'Caustic'), ('Wattson', 'Wattson')], max_length=60, verbose_name='Legend'),
        ),
    ]
