# Generated by Django 2.2.5 on 2021-06-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0019_auto_20210624_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Valkyrie', 'Valkyrie'), ('Wattson', 'Wattson'), ('Octane', 'Octane'), ('Mirage', 'Mirage'), ('Pathfinder', 'Pathfinder'), ('Bangalore', 'Bangalore'), ('Loba', 'Loba'), ('Crypto', 'Crypto'), ('Caustic', 'Caustic'), ('Wraith', 'Wraith'), ('Lifeline', 'Lifeline'), ('Revenant', 'Revenant'), ('Rampart', 'Rampart'), ('Fuse', 'Fuse'), ('Gibraltar', 'Gibraltar'), ('Bloodhound', 'Bloodhound'), ('Horizon', 'Horizon')], max_length=60, verbose_name='Legend'),
        ),
    ]
