# Generated by Django 2.2.5 on 2021-06-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0020_auto_20210624_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Bloodhound', 'Bloodhound'), ('Loba', 'Loba'), ('Octane', 'Octane'), ('Gibraltar', 'Gibraltar'), ('Bangalore', 'Bangalore'), ('Revenant', 'Revenant'), ('Valkyrie', 'Valkyrie'), ('Lifeline', 'Lifeline'), ('Fuse', 'Fuse'), ('Mirage', 'Mirage'), ('Rampart', 'Rampart'), ('Crypto', 'Crypto'), ('Wattson', 'Wattson'), ('Caustic', 'Caustic'), ('Pathfinder', 'Pathfinder'), ('Wraith', 'Wraith'), ('Horizon', 'Horizon')], max_length=60, verbose_name='Legend'),
        ),
    ]
