# Generated by Django 2.2.5 on 2021-06-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0021_auto_20210627_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Bangalore', 'Bangalore'), ('Horizon', 'Horizon'), ('Bloodhound', 'Bloodhound'), ('Fuse', 'Fuse'), ('Gibraltar', 'Gibraltar'), ('Pathfinder', 'Pathfinder'), ('Loba', 'Loba'), ('Revenant', 'Revenant'), ('Wattson', 'Wattson'), ('Rampart', 'Rampart'), ('Wraith', 'Wraith'), ('Mirage', 'Mirage'), ('Crypto', 'Crypto'), ('Valkyrie', 'Valkyrie'), ('Octane', 'Octane'), ('Caustic', 'Caustic'), ('Lifeline', 'Lifeline')], max_length=60, verbose_name='Legend'),
        ),
    ]
