# Generated by Django 2.2.5 on 2021-06-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0022_auto_20210627_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Horizon', 'Horizon'), ('Wraith', 'Wraith'), ('Octane', 'Octane'), ('Crypto', 'Crypto'), ('Gibraltar', 'Gibraltar'), ('Revenant', 'Revenant'), ('Lifeline', 'Lifeline'), ('Loba', 'Loba'), ('Pathfinder', 'Pathfinder'), ('Fuse', 'Fuse'), ('Rampart', 'Rampart'), ('Valkyrie', 'Valkyrie'), ('Bangalore', 'Bangalore'), ('Wattson', 'Wattson'), ('Mirage', 'Mirage'), ('Bloodhound', 'Bloodhound'), ('Caustic', 'Caustic')], max_length=60, verbose_name='Legend'),
        ),
    ]
