# Generated by Django 2.2.5 on 2021-06-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0023_auto_20210627_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Gibraltar', 'Gibraltar'), ('Fuse', 'Fuse'), ('Wraith', 'Wraith'), ('Mirage', 'Mirage'), ('Bangalore', 'Bangalore'), ('Crypto', 'Crypto'), ('Valkyrie', 'Valkyrie'), ('Rampart', 'Rampart'), ('Caustic', 'Caustic'), ('Wattson', 'Wattson'), ('Lifeline', 'Lifeline'), ('Octane', 'Octane'), ('Bloodhound', 'Bloodhound'), ('Revenant', 'Revenant'), ('Loba', 'Loba'), ('Pathfinder', 'Pathfinder'), ('Horizon', 'Horizon')], max_length=60, verbose_name='Legend'),
        ),
    ]
