# Generated by Django 2.2.5 on 2021-06-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0024_auto_20210627_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Rampart', 'Rampart'), ('Caustic', 'Caustic'), ('Fuse', 'Fuse'), ('Mirage', 'Mirage'), ('Horizon', 'Horizon'), ('Wattson', 'Wattson'), ('Lifeline', 'Lifeline'), ('Valkyrie', 'Valkyrie'), ('Revenant', 'Revenant'), ('Bloodhound', 'Bloodhound'), ('Gibraltar', 'Gibraltar'), ('Wraith', 'Wraith'), ('Loba', 'Loba'), ('Pathfinder', 'Pathfinder'), ('Bangalore', 'Bangalore'), ('Crypto', 'Crypto'), ('Octane', 'Octane')], max_length=60, verbose_name='Legend'),
        ),
    ]
