# Generated by Django 2.2.5 on 2022-03-06 01:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_name', models.CharField(max_length=50)),
                ('rotors', models.IntegerField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '8')], max_length=1)),
                ('battery', models.CharField(choices=[('2s', '2s'), ('3s', '3s'), ('4s', '4s'), ('5s', '5s'), ('6s', '6s')], max_length=1)),
                ('prop', models.IntegerField(max_length=10)),
                ('flight_time', models.IntegerField(max_length=10)),
            ],
            managers=[
                ('Drone', django.db.models.manager.Manager()),
            ],
        ),
    ]
