# Generated by Django 2.2.5 on 2022-03-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='drone',
            managers=[
            ],
        ),
    ]
