# Generated by Django 2.2.5 on 2021-12-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal_Type', models.CharField(choices=[('skill', 'Gain New Skill'), ('improve', 'Improve Existing Skill'), ('break', 'Break Bad Habit'), ('unsure', 'Not Sure')], max_length=25)),
                ('Your_Goal', models.CharField(max_length=100)),
                ('Reason', models.TextField(max_length=350)),
                ('Target_Range', models.CharField(choices=[('2wks', 'By 2-Weeks'), ('1mo', 'By 1-Month'), ('6wks', 'By 6-Weeks'), ('2mo', 'By 2-Months'), ('3mo', 'By 3-Months'), ('6mo', 'By 6-Months')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_Hours_Spent', models.CharField(choices=[('lt1', '<1'), ('1to3', '1-3'), ('4to6', '4-6'), ('gt6', '6+')], max_length=5)),
                ('Task_Completed', models.CharField(max_length=200)),
                ('Any_Challenges', models.CharField(max_length=200)),
                ('Other_Thoughts', models.CharField(max_length=200)),
                ('Goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyApp.Goals')),
            ],
        ),
    ]
