# Generated by Django 2.2.5 on 2021-12-24 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='StudyApp.Register'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='Goal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='StudyApp.Goals'),
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entry_Date', models.DateTimeField(auto_now=True)),
                ('Entry', models.TextField(max_length=400)),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='StudyApp.Register')),
            ],
        ),
    ]
