# Generated by Django 2.2.5 on 2021-12-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0002_auto_20211223_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='Your_Goal',
        ),
        migrations.AddField(
            model_name='diary',
            name='Daily_Hours_Spent',
            field=models.CharField(choices=[('lt1', '<1'), ('1to3', '1-3'), ('4to6', '4-6'), ('gt6', '6+')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='diary',
            name='Task_Completed',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='goals',
            name='Goal_Description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='goals',
            name='Goal_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='goals',
            name='Reason',
            field=models.TextField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='goals',
            name='Target_Range',
            field=models.CharField(choices=[('2wks', 'By 2-Weeks'), ('1mo', 'By 1-Month'), ('6wks', 'By 6-Weeks'), ('2mo', 'By 2-Months'), ('3mo', 'By 3-Months'), ('6mo', 'By 6-Months')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
