# Generated by Django 2.2.5 on 2021-12-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0003_auto_20211226_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='Task_Completed',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
