# Generated by Django 2.2.5 on 2022-04-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personality', '0002_auto_20220405_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=60),
        ),
    ]
