# Generated by Django 2.2.5 on 2022-04-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personality', '0009_auto_20220407_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=60),
        ),
    ]
