# Generated by Django 2.2.5 on 2021-07-07 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoteTaking', '0002_auto_20210701_1649'),
        ('NoteTaking', '0002_auto_20210701_1145'),
    ]

    operations = [
    ]
