# Generated by Django 2.2.5 on 2021-07-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstats', '0002_auto_20210720_1245'),
        ('NBAstats', '0002_auto_20210716_1232'),
    ]

    operations = [
    ]
