# Generated by Django 2.2.5 on 2022-03-31 21:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('comedy', 'Comedy'), ('anime', 'Anime'), ('horror', 'Horror'), ('sitcom', 'Sitcom'), ('musical', 'Musical'), ('slice of life', 'Slice of LIfe'), ('early animation', 'Early Animation')], default='Comedy', max_length=20)),
                ('network', models.CharField(max_length=30)),
                ('premier_date', models.DateField()),
                ('brief_description', models.TextField(default='', max_length=1000)),
            ],
            managers=[
                ('Cartoons', django.db.models.manager.Manager()),
            ],
        ),
    ]
