# Generated by Django 2.2.5 on 2022-04-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartoons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='genre',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('anime', 'Anime'), ('horror', 'Horror'), ('sitcom', 'Sitcom'), ('musical', 'Musical'), ('kids', 'Kids'), ('slice of life', 'Slice of LIfe'), ('early animation', 'Early Animation')], default='Comedy', max_length=20),
        ),
    ]
