# Generated by Django 2.2.5 on 2022-04-06 02:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Cartoons', '0002_auto_20220405_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('definition', models.TextField(max_length=100)),
            ],
            managers=[
                ('Definitions', django.db.models.manager.Manager()),
            ],
        ),
    ]
