# Generated by Django 2.2.5 on 2022-05-09 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('accounts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='receive_updates',
        ),
        migrations.AddField(
            model_name='account',
            name='coach_Grade',
            field=models.CharField(choices=[('4th-5th', '4th-5th'), ('6th-7th', '6th-7th'), ('K-1st', 'K-1st'), ('2nd-3rd', '2nd-3rd')], default='please choose', max_length=10),
        ),
        migrations.CreateModel(
            name='registerKids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('4th-5th', '4th-5th'), ('6th-7th', '6th-7th'), ('K-1st', 'K-1st'), ('2nd-3rd', '2nd-3rd')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.account')),
            ],
        ),
    ]
