# Generated by Django 2.2.5 on 2022-05-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Child_Grade',
            field=models.CharField(choices=[('K-1st', 'K-1st'), ('2nd-3rd', '2nd-3rd'), ('4th-5th', '4th-5th'), ('6th-7th', '6th-7th')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='Coach_Grade',
            field=models.CharField(choices=[('K-1st', 'K-1st'), ('2nd-3rd', '2nd-3rd'), ('4th-5th', '4th-5th'), ('6th-7th', '6th-7th')], max_length=10),
        ),
    ]
