# Generated by Django 2.2.5 on 2022-05-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20220509_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Child_Grade',
            field=models.CharField(choices=[('4th-5th', '4th-5th'), ('2nd-3rd', '2nd-3rd'), ('6th-7th', '6th-7th'), ('K-1st', 'K-1st')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='Coach_Grade',
            field=models.CharField(choices=[('4th-5th', '4th-5th'), ('2nd-3rd', '2nd-3rd'), ('6th-7th', '6th-7th'), ('K-1st', 'K-1st')], max_length=10),
        ),
    ]
