# Generated by Django 2.2.5 on 2022-05-09 21:32

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20220509_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='singupChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_Name', models.CharField(max_length=60)),
                ('grade', models.CharField(choices=[('2nd-3rd', '2nd-3rd'), ('4th-5th', '4th-5th'), ('K-1st', 'K-1st'), ('6th-7th', '6th-7th')], max_length=10)),
                ('Parent_Name', models.CharField(max_length=60)),
                ('Parent_Phone', models.CharField(max_length=60)),
                ('Parent_Email', models.CharField(max_length=60)),
            ],
            managers=[
                ('singupChild', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='coach_Grade',
            field=models.CharField(choices=[('2nd-3rd', '2nd-3rd'), ('4th-5th', '4th-5th'), ('K-1st', 'K-1st'), ('6th-7th', '6th-7th')], default='please choose', max_length=10),
        ),
        migrations.DeleteModel(
            name='registerKids',
        ),
    ]
