# Generated by Django 2.2.5 on 2022-05-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_auto_20220509_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='Child_Name',
            new_name='First_Name',
        ),
        migrations.AddField(
            model_name='child',
            name='Last_Name',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='Child_Grade',
            field=models.CharField(choices=[('2nd-3rd', '2nd-3rd'), ('6th-7th', '6th-7th'), ('K-1st', 'K-1st'), ('4th-5th', '4th-5th')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='Coach_Grade',
            field=models.CharField(choices=[('2nd-3rd', '2nd-3rd'), ('6th-7th', '6th-7th'), ('K-1st', 'K-1st'), ('4th-5th', '4th-5th')], max_length=10),
        ),
    ]
