# Generated by Django 2.2.5 on 2022-05-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_auto_20220509_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Notes_or_Allergies',
            field=models.TextField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='Child_Grade',
            field=models.CharField(choices=[('6th-7th', '6th-7th'), ('2nd-3rd', '2nd-3rd'), ('4th-5th', '4th-5th'), ('K-1st', 'K-1st')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='Coach_Grade',
            field=models.CharField(choices=[('6th-7th', '6th-7th'), ('2nd-3rd', '2nd-3rd'), ('4th-5th', '4th-5th'), ('K-1st', 'K-1st')], max_length=10),
        ),
    ]
