# Generated by Django 2.2.5 on 2021-04-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHOICES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YES', models.CharField(max_length=20)),
                ('NO', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrackApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('startTracking', 'startTracking'), ('dontTrack', 'dontTrack')], max_length=50)),
            ],
        ),
    ]
