# Generated by Django 2.2.5 on 2021-05-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApp', '0003_display'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Display',
        ),
    ]
