# Generated by Django 2.2.5 on 2022-03-28 15:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistFN', models.CharField(default='', max_length=100, verbose_name='Artist (Band or First Name)')),
                ('artistLN', models.CharField(blank=True, default='', max_length=100, verbose_name='Artist Last Name (if applicable)')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Album Title')),
                ('format', models.CharField(choices=[('VI', 'Vinyl'), ('CD', 'CD'), ('CA', 'Cassette'), ('OT', 'Other')], max_length=2, verbose_name='Format')),
                ('quality', models.CharField(blank=True, choices=[('MT', 'Mint'), ('NM', 'Near Mint'), ('EX', 'Excellent'), ('VG', 'Very Good'), ('GD', 'Good'), ('PR', 'Poor'), ('MT', 'Mint')], max_length=2, verbose_name='Condition')),
                ('rating', models.IntegerField(blank=True, choices=[(5, '5 Stars'), (4, '4 Stars'), (3, '3 Stars'), (2, '2 Stars'), (1, '1 Star')], verbose_name='Personal Rating')),
                ('comments', models.TextField(blank=True, default='', max_length=256, verbose_name='Notes')),
            ],
            managers=[
                ('Records', django.db.models.manager.Manager()),
            ],
        ),
    ]
