# Generated by Django 2.2.5 on 2022-01-27 19:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('rating', models.CharField(blank=True, default='', max_length=50)),
                ('director', models.CharField(blank=True, default='', max_length=100)),
                ('actor', models.CharField(blank=True, default='', max_length=100)),
                ('stars', models.CharField(choices=[('1 star', '1 star'), ('2 stars', '2 stars'), ('3 stars', '3 stars'), ('4 stars', '4 stars'), ('5 stars', '5 stars')], max_length=100)),
            ],
            managers=[
                ('Movies', django.db.models.manager.Manager()),
            ],
        ),
    ]
