# Generated by Django 2.2.5 on 2022-03-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChefKnives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brands', models.CharField(max_length=60)),
                ('price', models.IntegerField(default='')),
                ('country_origin', models.CharField(max_length=60)),
                ('steal', models.CharField(max_length=60)),
                ('blade_style', models.CharField(max_length=60)),
            ],
        ),
    ]
