# Generated by Django 2.2.5 on 2022-07-26 01:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('legs', 'legs'), ('abs', 'abs'), ('back', 'back'), ('arms', 'arms')], max_length=90)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(max_length=90)),
                ('calories', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('Entries', django.db.models.manager.Manager()),
            ],
        ),
    ]
