# Generated by Django 2.2.5 on 2022-06-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(choices=[('legs', 'legs'), ('back', 'back'), ('abs', 'abs'), ('arms', 'arms')], max_length=90),
        ),
    ]
