# Generated by Django 2.2.5 on 2021-06-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HipHopReviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='AlbumGenre',
        ),
    ]
