# Generated by Django 2.2.5 on 2021-06-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HipHopReviews', '0002_remove_reviews_albumgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ReleaseYear',
            field=models.IntegerField(blank=True),
        ),
    ]
