# Generated by Django 2.2.5 on 2022-03-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('legs', 'legs'), ('back', 'back'), ('chest', 'chest'), ('arms', 'arms'), ('core', 'core')], max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
