# Generated by Django 2.2.5 on 2021-11-19 02:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Rock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hardrock',
            managers=[
                ('HardRock', django.db.models.manager.Manager()),
            ],
        ),
    ]
