# Generated by Django 2.2.5 on 2021-11-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rock', '0002_auto_20211118_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardrock',
            old_name='artist',
            new_name='Band',
        ),
    ]
