# Generated by Django 2.2.5 on 2021-11-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rock', '0003_auto_20211119_1900'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hardrock',
            managers=[
            ],
        ),
    ]
