# Generated by Django 2.2.5 on 2021-05-05 23:08

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebScrape',
            fields=[
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Pet Supplies', 'Pet Supplies'), ('Vehicles', 'Vehicles')], max_length=50)),
                ('url', models.URLField(default='', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('imageUrl', models.URLField()),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            managers=[
                ('WebScrape_db', django.db.models.manager.Manager()),
            ],
        ),
    ]
