# Generated by Django 2.2.5 on 2021-05-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resellers_MarketWatch', '0002_userlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webscrape',
            name='category',
            field=models.CharField(choices=[(None, 'Select Category'), ('Electronics', 'Electronics'), ('Pet Supplies', 'Pet Supplies'), ('Vehicles', 'Vehicles')], max_length=50),
        ),
    ]
