# Generated by Django 2.2.5 on 2022-07-04 17:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorSize', models.CharField(choices=[('M4/3', 'M4/3'), ('APS-C', 'APS-C'), ('Medium', 'Medium'), ('Full_Frame', 'Full_Frame')], max_length=10)),
                ('lensFocal', models.CharField(choices=[('50mm', '50mm'), ('35mm', '35mm'), ('24mm', '24mm'), ('85mm', '85mm')], max_length=5)),
                ('manufacturer', models.CharField(default='', max_length=15)),
            ],
            managers=[
                ('Camera', django.db.models.manager.Manager()),
            ],
        ),
    ]
