# Generated by Django 2.2.5 on 2022-06-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinematography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofview',
            name='lensFocal',
            field=models.CharField(choices=[('85mm', '85mm'), ('35mm', '35mm'), ('24mm', '24mm'), ('50mm', '50mm')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fieldofview',
            name='sensorSize',
            field=models.CharField(choices=[('M4/3', 'M4/3'), ('Full_Frame', 'Full_Frame'), ('Medium', 'Medium'), ('APS-C', 'APS-C')], max_length=10),
        ),
    ]
