# Generated by Django 2.2.5 on 2022-03-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutEquipment', '0002_auto_20220310_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutequipment',
            name='type',
            field=models.CharField(choices=[('stationary bikes', 'stationary bikes'), ('Free weights', 'Free weights'), ('treadmills', 'treadmills'), ('benches', 'benches')], max_length=60),
        ),
    ]
