# Generated by Django 2.2.5 on 2022-03-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutEquipment', '0002_auto_20220305_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutequipment',
            name='type',
            field=models.CharField(choices=[('treadmills', 'treadmills'), ('Free weights', 'Free weights'), ('benches', 'benches'), ('stationary bikes', 'stationary bikes')], max_length=60),
        ),
    ]
