# Generated by Django 2.2.5 on 2022-03-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutEquipment', '0003_auto_20220311_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutequipment',
            name='type',
            field=models.CharField(choices=[('Free weights', 'Free weights'), ('benches', 'benches'), ('treadmills', 'treadmills'), ('stationary bikes', 'stationary bikes')], max_length=60),
        ),
    ]
