# Generated by Django 2.2.5 on 2022-03-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutEquipment', '0003_auto_20220305_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutequipment',
            name='type',
            field=models.CharField(choices=[('benches', 'benches'), ('Free weights', 'Free weights'), ('stationary bikes', 'stationary bikes'), ('treadmills', 'treadmills')], max_length=60),
        ),
    ]
