# Generated by Django 2.2.5 on 2022-03-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutEquipment', '0003_auto_20220307_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutequipment',
            name='type',
            field=models.CharField(choices=[('benches', 'benches'), ('stationary bikes', 'stationary bikes'), ('Free weights', 'Free weights'), ('treadmills', 'treadmills')], max_length=60),
        ),
    ]
