# Generated by Django 2.2.5 on 2022-03-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutEquipment', '0004_auto_20220307_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutequipment',
            name='type',
            field=models.CharField(choices=[('Free weights', 'Free weights'), ('benches', 'benches'), ('treadmills', 'treadmills'), ('stationary bikes', 'stationary bikes')], max_length=60),
        ),
    ]
