SUBJECT = [
    ('CH', 'Cheerful'),
    ('RE', 'Reflective'),
    ('GL', 'Gloomy'),
    ('HU', 'Humorous'),
    ('ME', 'Melancholy'),
    ('ID', 'Idyllic'),
    ('WH', 'Whimsical'),
    ('RO', 'Romantic'),
    ('MY', 'Mysterious'),
    ('OM', 'Ominous'),
    ('CA', 'Calm'),
    ('LI', 'Lighthearted'),
    ('HO', 'Hopeful'),
    ('AN', 'Angry'),
    ('FE', 'Fearful'),
    ('TE', 'Tense'),
    ('LO', 'Lonely'),
    ('IN', 'Inspirational'),
]