# Generated by Django 2.2.5 on 2022-07-26 01:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('chemical_category', models.CharField(choices=[('Inorganic Salt', 'Inorganic Salt'), ('Organic Salt', 'Organic Salt'), ('Acid', 'Acid'), ('Base', 'Base'), ('Surfactant', 'Surfactant'), ('Solvent', 'Solvent'), ('Finished Product', 'Finished Product'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('chemical_description', models.CharField(max_length=300)),
                ('hazards', models.CharField(choices=[('Toxic', 'Toxic'), ('Corrosive', 'Corrosive'), ('Reactive', 'Reactive'), ('Flammable', 'Flammable'), ('None', 'None')], max_length=30)),
            ],
            managers=[
                ('Materials', django.db.models.manager.Manager()),
            ],
        ),
    ]
