# Generated by Django 2.2.5 on 2021-04-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterApp', '0006_auto_20210430_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_create',
            name='race',
            field=models.CharField(choices=[('Orc', 'Orc'), ('Troll', 'Troll'), ('Gnome', 'Gnome'), ('Human', 'Human'), ('Undead', 'Undead'), ('Dranei', 'Dranei'), ('Blood Elf', 'Blood Elf'), ('Night Elf', 'Night Elf')], max_length=60),
        ),
        migrations.AlterField(
            model_name='character_create',
            name='sex',
            field=models.CharField(choices=[('Other', 'Other'), ('Male', 'Male'), ('Female', 'Female')], max_length=60),
        ),
    ]
