# Generated by Django 2.2.5 on 2021-05-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterApp', '0007_auto_20210430_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_create',
            name='race',
            field=models.CharField(choices=[('Orc', 'Orc'), ('Troll', 'Troll'), ('Undead', 'Undead'), ('Blood Elf', 'Blood Elf'), ('Human', 'Human'), ('Night Elf', 'Night Elf'), ('Gnome', 'Gnome'), ('Dranei', 'Dranei')], max_length=60),
        ),
        migrations.AlterField(
            model_name='character_create',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=60),
        ),
    ]
