# Generated by Django 2.2.5 on 2021-10-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_auto_20211001_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Dessert', 'Dessert'), ('Dinner', 'Dinner'), ('Lunch', 'Lunch'), ('Breakfast', 'Breakfast')], max_length=9),
        ),
    ]
