# Generated by Django 2.2.5 on 2021-09-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0003_auto_20210930_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dessert', 'Dessert'), ('Breakfast', 'Breakfast'), ('Dinner', 'Dinner')], max_length=9),
        ),
    ]
