# Generated by Django 2.2.5 on 2021-10-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0003_auto_20211001_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Lunch', 'Lunch')], max_length=9),
        ),
    ]
