# Generated by Django 2.2.5 on 2021-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0005_auto_20211003_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dessert', 'Dessert'), ('Dinner', 'Dinner'), ('Breakfast', 'Breakfast')], max_length=9),
        ),
    ]
