# Generated by Django 2.2.5 on 2021-10-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0008_auto_20210930_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert')], max_length=9),
        ),
    ]
