# Generated by Django 2.2.5 on 2021-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0008_auto_20211003_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dessert', 'Dessert'), ('Dinner', 'Dinner')], max_length=9),
        ),
    ]
