# Generated by Django 2.2.5 on 2021-10-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0009_auto_20211004_1056'),
        ('Recipes', '0009_auto_20210930_1757'),
    ]

    operations = [
    ]
