# Generated by Django 2.2.5 on 2021-10-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0009_auto_20211003_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dessert', 'Dessert'), ('Breakfast', 'Breakfast'), ('Dinner', 'Dinner')], max_length=9),
        ),
    ]
