# Generated by Django 2.2.5 on 2021-10-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0010_auto_20211003_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Dinner', 'Dinner'), ('Breakfast', 'Breakfast'), ('Dessert', 'Dessert'), ('Lunch', 'Lunch')], max_length=9),
        ),
    ]
