# Generated by Django 2.2.5 on 2021-10-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0011_auto_20211003_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Dinner', 'Dinner'), ('Lunch', 'Lunch'), ('Dessert', 'Dessert'), ('Breakfast', 'Breakfast')], max_length=9),
        ),
    ]
