# Generated by Django 2.2.5 on 2021-10-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0012_auto_20211003_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Dessert', 'Dessert'), ('Dinner', 'Dinner'), ('Lunch', 'Lunch')], max_length=9),
        ),
    ]
