# Generated by Django 2.2.5 on 2021-10-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0015_auto_20211004_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Dessert', 'Dessert'), ('Dinner', 'Dinner'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch')], max_length=9),
        ),
    ]
