# Generated by Django 2.2.5 on 2021-10-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0016_auto_20211005_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Breakfast', 'Breakfast'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert')], max_length=9),
        ),
    ]
