# Generated by Django 2.2.5 on 2022-03-08 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockHolderCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockCompanyName', models.CharField(max_length=100)),
                ('CompanyAddress', models.CharField(max_length=100)),
                ('FullTimeStatus', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='StockUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockHolderName', models.CharField(max_length=50)),
                ('StockHolderAddress', models.CharField(max_length=150)),
                ('StockHolderPhone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockTicker', models.CharField(max_length=20)),
                ('StockPrice', models.FloatField()),
                ('StockAmount', models.FloatField()),
                ('StockCompanyName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StockTracker.StockHolderCompany')),
                ('StockHolderName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StockTracker.StockUser')),
            ],
        ),
    ]
