# Generated by Django 2.2.5 on 2021-11-29 19:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Campsites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='campsites',
            managers=[
                ('Sites', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('Location', django.db.models.manager.Manager()),
            ],
        ),
    ]
