# Generated by Django 2.2.5 on 2022-05-17 17:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Builds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('case_size', models.CharField(choices=[('full tower', 'Full Tower'), ('mid-tower', 'Mid-Tower'), ('mini-tower', 'Mini-Tower'), ('small form factor', 'Small Form Factor')], max_length=30)),
                ('Specifications', models.TextField(default='', max_length=255)),
            ],
            managers=[
                ('Builds', django.db.models.manager.Manager()),
            ],
        ),
    ]
