# Generated by Django 2.2.5 on 2021-10-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('city', models.CharField(help_text='Which city are we talking about?', max_length=200, primary_key=True, serialize=False)),
                ('timeZone', models.CharField(choices=[('1', 'Azores'), ('2', 'Iceland'), ('3', 'Portugal, UK, Canary Islands'), ('4', 'Western Europe, Scandinavia, Central Europe'), ('5', 'Finland, Ukraine, Romania, Greece'), ('6', 'Belarus, Western Russia, Turkey'), ('7', 'Georgia, Azerbaijan')], help_text="Please select from the list, to convert it's time zone.", max_length=200)),
                ('safety', models.CharField(choices=[('1', 'Not safe at all'), ('2', 'Not safe, would not bring family'), ('3', 'Decently safe, just be careful and wise'), ('4', 'No safety threats, but there are areas I would not go'), ('5', 'Really safe, my grandma would be ok')], help_text='Please choose a safety rating for this location.', max_length=200)),
                ('prices', models.CharField(choices=[('1', 'Extremely cheap to visit'), ('2', 'Not the cheapest, but close'), ('3', 'Average price'), ('4', 'A little lavish'), ('5', 'Only for the high rollers')], help_text='Please consider the total price of the trip when rating', max_length=150)),
            ],
        ),
    ]
