# Generated by Django 2.2.5 on 2021-10-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EuroTrip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(help_text='Which country are we talking about?', max_length=200, primary_key=True, serialize=False),
        ),
    ]
