# Generated by Django 2.2.5 on 2022-01-27 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=50)),
                ('collection_type', models.CharField(choices=[('General', 'General'), ('Standard', 'Standard'), ('Modern', 'Modern'), ('Legacy', 'Legacy'), ('Vintage', 'Vintage'), ('Commander', 'Commander')], max_length=60)),
            ],
            managers=[
                ('Collection', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=50)),
                ('card_color', models.CharField(choices=[('White', 'White'), ('Blue', 'Blue'), ('Black', 'Black'), ('Red', 'Red'), ('Green', 'Green'), ('Multi', 'Multi'), ('Colorless', 'Colorless')], max_length=10)),
                ('card_cost', models.CharField(max_length=10)),
                ('card_type', models.CharField(choices=[('Creature', 'Creature'), ('Instant', 'Instant'), ('Sorcery', 'Sorcery'), ('Land', 'Land'), ('Enchantment', 'Enchantment'), ('Artifact', 'Artifact'), ('Plainswalker', 'Plainswalker')], max_length=15)),
                ('card_text', models.CharField(max_length=250)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MagicTheGathering.Collection')),
            ],
            managers=[
                ('Cards', django.db.models.manager.Manager()),
            ],
        ),
    ]
