# Generated by Django 2.2.5 on 2022-05-09 03:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('Food', 'Food'), ('Hotel', 'Hotel'), ('Parking', 'Parking'), ('Parks', 'Parks'), ('Attraction', 'Attraction')], default='', max_length=50)),
                ('Place', models.CharField(blank=True, default='', max_length=20)),
                ('Description', models.CharField(blank=True, default='', max_length=500)),
            ],
            managers=[
                ('PlacesManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
