# Generated by Django 2.2.5 on 2022-03-24 00:29

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Cookies', 'Cookies'), ('Cakes', 'Cakes'), ('Pies', 'Pies'), ('Cupcakes', 'Cupcakes'), ('Bars', 'Bars'), ('Cheesecakes', 'Cheesecakes'), ('Brownies', 'Brownies'), ('Other', 'Other')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('ingredients', models.TextField(blank=True, default='', max_length=1000)),
                ('method', models.TextField(blank=True, default='', max_length=1000)),
                ('servings', models.IntegerField()),
            ],
            managers=[
                ('Recipes', django.db.models.manager.Manager()),
            ],
        ),
    ]
