# Generated by Django 2.2.5 on 2022-06-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('number_of_ingredients', models.IntegerField()),
                ('making_time', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
