# Generated by Django 2.2.5 on 2021-08-06 18:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newpasswords',
            managers=[
                ('NewPasswords', django.db.models.manager.Manager()),
            ],
        ),
    ]
