# Generated by Django 2.2.5 on 2021-08-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0002_auto_20210806_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpasswords',
            name='email',
            field=models.EmailField(max_length=160),
        ),
    ]
