# Generated by Django 2.2.5 on 2021-09-14 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0002_auto_20210914_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='sets',
            field=models.IntegerField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms')], max_length=60),
        ),
    ]
