# Generated by Django 2.2.5 on 2021-09-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0003_auto_20210914_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Arms', 'Arms'), ('Chest', 'Chest'), ('Shoulders', 'Shoulders'), ('Legs', 'Legs'), ('Back', 'Back')], max_length=60),
        ),
    ]
