# Generated by Django 2.2.5 on 2021-09-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0004_auto_20210914_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='repetitions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='sets',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs')], max_length=60),
        ),
    ]
