# Generated by Django 2.2.5 on 2021-09-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0005_auto_20210914_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='repetitions',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='sets',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Back', 'Back'), ('Chest', 'Chest')], max_length=60),
        ),
    ]
