# Generated by Django 2.2.5 on 2021-09-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0008_auto_20210914_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='repetitions',
            field=models.IntegerField(verbose_name=15),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='sets',
            field=models.IntegerField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Back', 'Back'), ('Arms', 'Arms'), ('Chest', 'Chest')], max_length=60),
        ),
    ]
