# Generated by Django 2.2.5 on 2021-09-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0010_auto_20210914_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Shoulders', 'Shoulders'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Back', 'Back'), ('Chest', 'Chest')], max_length=60),
        ),
    ]
