# Generated by Django 2.2.5 on 2021-09-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0011_auto_20210914_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='repetitions',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='sets',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Shoulders', 'Shoulders'), ('Back', 'Back'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Chest', 'Chest')], max_length=60),
        ),
    ]
