# Generated by Django 2.2.5 on 2021-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0012_auto_20210914_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='repetitions',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='sets',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Arms', 'Arms'), ('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Legs', 'Legs')], max_length=60),
        ),
    ]
