# Generated by Django 2.2.5 on 2021-09-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0013_auto_20210914_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='repetitions',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='sets',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Arms', 'Arms'), ('Chest', 'Chest'), ('Shoulders', 'Shoulders'), ('Back', 'Back'), ('Legs', 'Legs')], max_length=60),
        ),
    ]
