# Generated by Django 2.2.5 on 2021-09-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0014_auto_20210914_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Arms', 'Arms'), ('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders')], max_length=60),
        ),
    ]
