# Generated by Django 2.2.5 on 2021-09-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0015_auto_20210914_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='sets',
        ),
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Legs', 'Legs'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms')], max_length=60),
        ),
    ]
