# Generated by Django 2.2.5 on 2021-09-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0018_auto_20210914_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='sets',
        ),
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Back', 'Back'), ('Chest', 'Chest'), ('Shoulders', 'Shoulders'), ('Legs', 'Legs'), ('Arms', 'Arms')], max_length=60),
        ),
    ]
