# Generated by Django 2.2.5 on 2021-09-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0020_auto_20210914_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='sets',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Chest', 'Chest'), ('Back', 'Back')], max_length=60),
        ),
    ]
