# Generated by Django 2.2.5 on 2022-06-02 10:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=50)),
                ('activity_snacks', models.CharField(max_length=50)),
                ('activity_description', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=0, default='', max_digits=5)),
            ],
            managers=[
                ('Entries', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherMoment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('WeatherMoment', django.db.models.manager.Manager()),
            ],
        ),
    ]
