# Generated by Django 2.2.5 on 2022-05-09 03:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=50)),
                ('activity_snacks', models.CharField(max_length=50)),
                ('activity_description', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=0, default='', max_digits=5)),
            ],
            managers=[
                ('ActivitiesManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
