# Generated by Django 2.2.5 on 2021-11-18 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotSprings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_springs_name', models.CharField(max_length=50)),
                ('hot_springs_type', models.CharField(choices=[('Both', 'Both'), ('Outdoor', 'Outdoor'), ('Indoor', 'Indoor')], max_length=60)),
                ('clothing_optional', models.CharField(choices=[('Optional', 'Optional'), ('Required', 'Required')], max_length=60)),
                ('stay_accomondations', models.CharField(choices=[('Cabin Rentals', 'Cabin Rentals'), ('Tent Camping', 'Tent Camping'), ('Camping & Rentals', 'Camping & Rentals'), ('Resort', 'Resort'), ('Trailer Hookups', 'Trailer Hookups'), ('No Overnight Stay', 'No Overnight Stay')], max_length=60)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('hotsprings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HotSprings.HotSprings')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
            bases=('HotSprings.hotsprings',),
        ),
    ]
