# Generated by Django 2.2.5 on 2021-11-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotSprings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsprings',
            name='hot_springs_type',
            field=models.CharField(choices=[('Outdoor', 'Outdoor'), ('Indoor', 'Indoor'), ('Both', 'Both')], max_length=60),
        ),
        migrations.AlterField(
            model_name='hotsprings',
            name='stay_accomondations',
            field=models.CharField(choices=[('Camping & Rentals', 'Camping & Rentals'), ('Cabin Rentals', 'Cabin Rentals'), ('No Overnight Stay', 'No Overnight Stay'), ('Tent Camping', 'Tent Camping'), ('Resort', 'Resort'), ('Trailer Hookups', 'Trailer Hookups')], max_length=60),
        ),
    ]
