# Generated by Django 2.2.5 on 2021-11-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotSprings', '0002_auto_20211118_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsprings',
            name='clothing_optional',
            field=models.CharField(choices=[('Optional', 'Optional'), ('Required', 'Required')], max_length=60),
        ),
        migrations.AlterField(
            model_name='hotsprings',
            name='stay_accomondations',
            field=models.CharField(choices=[('No Overnight Stay', 'No Overnight Stay'), ('Trailer Hookups', 'Trailer Hookups'), ('Camping & Rentals', 'Camping & Rentals'), ('Resort', 'Resort'), ('Cabin Rentals', 'Cabin Rentals'), ('Tent Camping', 'Tent Camping')], max_length=60),
        ),
    ]
