# Generated by Django 2.2.5 on 2021-11-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotSprings', '0003_auto_20211119_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsprings',
            name='hot_springs_type',
            field=models.CharField(choices=[('Both', 'Both'), ('Outdoor', 'Outdoor'), ('Indoor', 'Indoor')], max_length=60),
        ),
        migrations.AlterField(
            model_name='hotsprings',
            name='stay_accomondations',
            field=models.CharField(choices=[('Tent Camping', 'Tent Camping'), ('Camping & Rentals', 'Camping & Rentals'), ('No Overnight Stay', 'No Overnight Stay'), ('Trailer Hookups', 'Trailer Hookups'), ('Cabin Rentals', 'Cabin Rentals'), ('Resort', 'Resort')], max_length=60),
        ),
    ]
