# Generated by Django 2.2.5 on 2021-11-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotSprings', '0004_auto_20211119_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsprings',
            name='clothing_optional',
            field=models.CharField(choices=[('Required', 'Required'), ('Optional', 'Optional')], max_length=60),
        ),
        migrations.AlterField(
            model_name='hotsprings',
            name='hot_springs_type',
            field=models.CharField(choices=[('Both', 'Both'), ('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=60),
        ),
        migrations.AlterField(
            model_name='hotsprings',
            name='stay_accomondations',
            field=models.CharField(choices=[('Tent Camping', 'Tent Camping'), ('Camping & Rentals', 'Camping & Rentals'), ('No Overnight Stay', 'No Overnight Stay'), ('Resort', 'Resort'), ('Cabin Rentals', 'Cabin Rentals'), ('Trailer Hookups', 'Trailer Hookups')], max_length=60),
        ),
    ]
