# Generated by Django 2.2.5 on 2021-11-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotSprings', '0005_auto_20211119_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotsprings',
            name='stay_accomondations',
        ),
        migrations.AddField(
            model_name='hotsprings',
            name='stay_accommodations',
            field=models.CharField(choices=[('Tent Camping', 'Tent Camping'), ('Trailer Hookups', 'Trailer Hookups'), ('Cabin Rentals', 'Cabin Rentals'), ('Resort', 'Resort'), ('Camping & Rentals', 'Camping & Rentals'), ('No Overnight Stay', 'No Overnight Stay')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='hotsprings',
            name='hot_springs_type',
            field=models.CharField(choices=[('Outdoor', 'Outdoor'), ('Indoor', 'Indoor'), ('Both', 'Both')], max_length=60),
        ),
    ]
