# Generated by Django 2.2.5 on 2021-07-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RidleyVerse', '0002_youtuber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Youtuber',
        ),
    ]
