# Generated by Django 2.2.5 on 2022-01-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yoga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Hatha', 'Hatha'), ('Iyengar', 'Iyengar'), ('Vinyasa ', 'Vinyasa '), ('Hot yoga', 'Hot yoga'), ('Ashtanga', 'Ashtanga')], max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('benefits', models.CharField(max_length=200)),
            ],
        ),
    ]
