# Generated by Django 2.2.5 on 2021-10-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FunkoCollector', '0002_auto_20211015_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funkopopname',
            name='size',
            field=models.CharField(choices=[('Regular', '4_inch'), ('Medium', '6_inch'), ('Jumbo', '10_inch')], max_length=7),
        ),
    ]
