# Generated by Django 2.2.5 on 2022-01-27 19:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Propulsion', models.CharField(choices=[('Jet', 'Jet'), ('Turboprop', 'Turboprop')], default='', max_length=20)),
                ('Manufacture', models.CharField(choices=[('Boeing', 'Boeing'), ('Airbus', 'Airbus'), ('Bombardier', 'Bombardier')], default='', max_length=20)),
                ('AircraftType', models.CharField(choices=[('Widebody', 'Widebody'), ('Narrowbody', 'Narrowbody')], default='', max_length=20)),
                ('ModelNumber', models.CharField(default='', max_length=20)),
                ('Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
            managers=[
                ('Plane', django.db.models.manager.Manager()),
            ],
        ),
    ]
