# Generated by Django 2.2.5 on 2022-01-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacture', models.CharField(choices=[('Boeing', 'Boeing'), ('Airbus', 'Airbus'), ('Bombardier', 'Bombardier')], default='', max_length=20)),
                ('Size', models.CharField(choices=[('Widebody', 'Widenody'), ('Narrowbody', 'Narrowbody')], default='', max_length=20)),
                ('Propulsion', models.CharField(choices=[('Jet', 'Jet'), ('Turboprop', 'Turboprop')], default='', max_length=20)),
                ('Model', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
