# Generated by Django 2.2.5 on 2022-01-14 01:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialAirplanes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='airplane',
            managers=[
                ('Plane', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='airplane',
            old_name='Size',
            new_name='AircraftType',
        ),
    ]
