# Generated by Django 2.2.5 on 2022-01-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialAirplanes', '0002_auto_20220114_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
