# Generated by Django 2.2.5 on 2022-01-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComercialAirplanes', '0003_airplane_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='Model',
            new_name='ModelNumber',
        ),
    ]
