# Generated by Django 2.2.5 on 2022-05-19 17:36

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('Users', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Workout',
        ),
        migrations.AlterField(
            model_name='user',
            name='BMI',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='Calories',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='FatPercent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='Protein',
            field=models.IntegerField(default=''),
        ),
    ]
