# Generated by Django 2.2.5 on 2022-04-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default='')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('NB', 'Non-Binary'), ('O', 'Other')], max_length=15)),
                ('species', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=100)),
                ('alignment', models.CharField(blank=True, choices=[('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('TN', 'True Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil')], max_length=19)),
                ('series', models.CharField(max_length=100)),
            ],
        ),
    ]
