# Generated by Django 2.2.5 on 2022-04-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FictionalCharacters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('BOOK', 'Book'), ('CMC', 'Comic'), ('FILM', 'Movie'), ('TV', 'Television Series'), ('VG', 'Video Game'), ('OTH', 'Other')], max_length=20)),
                ('creator', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='characters',
            name='alignment',
            field=models.CharField(blank=True, choices=[('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('TN', 'True Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil')], max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='characters',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FictionalCharacters.Series'),
        ),
    ]
