# Generated by Django 2.2.5 on 2021-07-08 05:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Villager_Registry', '0002_auto_20210707_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('image', models.CharField(default='', max_length=30)),
                ('species', models.CharField(default='', max_length=20)),
                ('birthday', models.CharField(default='', max_length=25)),
                ('hobbies', models.CharField(default='', max_length=20)),
            ],
            managers=[
                ('Residents', django.db.models.manager.Manager()),
            ],
        ),
    ]
