# Generated by Django 2.2.5 on 2021-07-08 06:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Villager_Registry', '0003_resident'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='resident',
            managers=[
                ('residents', django.db.models.manager.Manager()),
            ],
        ),
    ]
