# Generated by Django 2.2.5 on 2021-12-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Character_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Character_Class', models.CharField(choices=[('Cleric', 'Cleric'), ('Wizard', 'Wizard'), ('Warlock', 'Warlock'), ('Bard', 'Bard'), ('Barbarian', 'Barbarian'), ('Sorcerer', 'Sorcerer'), ('Druid', 'Driud'), ('Ranger', 'Ranger'), ('Fighter', 'Fighter')], max_length=60)),
                ('background', models.TextField(blank=True, default='', max_length=300)),
                ('Strength', models.IntegerField(choices=[(8, 8), (17, 17), (14, 14), (16, 16), (9, 9), (13, 13), (10, 10), (12, 12), (18, 18), (11, 11), (15, 15)])),
                ('Dexterity', models.IntegerField(choices=[(8, 8), (17, 17), (14, 14), (16, 16), (9, 9), (13, 13), (10, 10), (12, 12), (18, 18), (11, 11), (15, 15)])),
                ('Constitution', models.IntegerField(choices=[(8, 8), (17, 17), (14, 14), (16, 16), (9, 9), (13, 13), (10, 10), (12, 12), (18, 18), (11, 11), (15, 15)])),
                ('Intellegence', models.IntegerField(choices=[(8, 8), (17, 17), (14, 14), (16, 16), (9, 9), (13, 13), (10, 10), (12, 12), (18, 18), (11, 11), (15, 15)])),
                ('Wisdom', models.IntegerField(choices=[(8, 8), (17, 17), (14, 14), (16, 16), (9, 9), (13, 13), (10, 10), (12, 12), (18, 18), (11, 11), (15, 15)])),
                ('Charisma', models.IntegerField(choices=[(8, 8), (17, 17), (14, 14), (16, 16), (9, 9), (13, 13), (10, 10), (12, 12), (18, 18), (11, 11), (15, 15)])),
            ],
        ),
    ]
