# Generated by Django 2.2.5 on 2021-12-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Character_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Character_Class', models.CharField(choices=[('Warlock', 'Warlock'), ('Fighter', 'Fighter'), ('Ranger', 'Ranger'), ('Bard', 'Bard'), ('Druid', 'Driud'), ('Wizard', 'Wizard'), ('Cleric', 'Cleric'), ('Sorcerer', 'Sorcerer'), ('Barbarian', 'Barbarian')], max_length=60)),
                ('Strength', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], unique=True)),
                ('Dexterity', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], unique=True)),
                ('Constitution', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], unique=True)),
                ('Intellegence', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], unique=True)),
                ('Wisdom', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], unique=True)),
                ('Charisma', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], unique=True)),
                ('Background', models.TextField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
