# Generated by Django 2.2.5 on 2021-12-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Fighter', 'Fighter'), ('Barbarian', 'Barbarian'), ('Ranger', 'Ranger'), ('Cleric', 'Cleric'), ('Druid', 'Driud'), ('Wizard', 'Wizard'), ('Bard', 'Bard'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock')], max_length=60),
        ),
    ]
