# Generated by Django 2.2.5 on 2021-12-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0002_auto_20211216_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Barbarian', 'Barbarian'), ('Fighter', 'Fighter'), ('Bard', 'Bard'), ('Sorcerer', 'Sorcerer'), ('Ranger', 'Ranger'), ('Wizard', 'Wizard'), ('Warlock', 'Warlock'), ('Cleric', 'Cleric'), ('Druid', 'Driud')], max_length=60),
        ),
    ]
