# Generated by Django 2.2.5 on 2021-12-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0002_auto_20211219_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Cleric', 'Cleric'), ('Wizard', 'Wizard'), ('Bard', 'Bard'), ('Warlock', 'Warlock'), ('Barbarian', 'Barbarian'), ('Sorcerer', 'Sorcerer'), ('Fighter', 'Fighter'), ('Druid', 'Driud'), ('Ranger', 'Ranger')], max_length=60),
        ),
    ]
