# Generated by Django 2.2.5 on 2021-12-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0002_auto_20211220_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Charisma',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)]),
        ),
        migrations.AlterField(
            model_name='characters',
            name='Constitution',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)]),
        ),
        migrations.AlterField(
            model_name='characters',
            name='Dexterity',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)]),
        ),
        migrations.AlterField(
            model_name='characters',
            name='Intellegence',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)]),
        ),
        migrations.AlterField(
            model_name='characters',
            name='Strength',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)]),
        ),
        migrations.AlterField(
            model_name='characters',
            name='Wisdom',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)]),
        ),
    ]
