# Generated by Django 2.2.5 on 2021-12-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0003_auto_20211219_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Fighter', 'Fighter'), ('Cleric', 'Cleric'), ('Ranger', 'Ranger'), ('Wizard', 'Wizard'), ('Druid', 'Driud'), ('Sorcerer', 'Sorcerer'), ('Bard', 'Bard'), ('Warlock', 'Warlock'), ('Barbarian', 'Barbarian')], max_length=60),
        ),
    ]
