# Generated by Django 2.2.5 on 2021-12-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0004_auto_20211216_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Sorcerer', 'Sorcerer'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Wizard', 'Wizard'), ('Druid', 'Driud'), ('Warlock', 'Warlock'), ('Fighter', 'Fighter'), ('Barbarian', 'Barbarian'), ('Ranger', 'Ranger')], max_length=60),
        ),
    ]
