# Generated by Django 2.2.5 on 2021-12-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0004_auto_20211219_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Wizard', 'Wizard'), ('Fighter', 'Fighter'), ('Druid', 'Driud'), ('Warlock', 'Warlock'), ('Sorcerer', 'Sorcerer'), ('Cleric', 'Cleric'), ('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Ranger', 'Ranger')], max_length=60),
        ),
    ]
