# Generated by Django 2.2.5 on 2021-12-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0005_auto_20211220_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Ranger', 'Ranger'), ('Warlock', 'Warlock'), ('Druid', 'Driud'), ('Sorcerer', 'Sorcerer'), ('Wizard', 'Wizard'), ('Cleric', 'Cleric'), ('Fighter', 'Fighter'), ('Barbarian', 'Barbarian'), ('Bard', 'Bard')], max_length=60),
        ),
    ]
