# Generated by Django 2.2.5 on 2021-12-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0005_auto_20211216_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Fighter', 'Fighter'), ('Cleric', 'Cleric'), ('Ranger', 'Ranger'), ('Sorcerer', 'Sorcerer'), ('Barbarian', 'Barbarian'), ('Druid', 'Driud'), ('Warlock', 'Warlock'), ('Bard', 'Bard'), ('Wizard', 'Wizard')], max_length=60),
        ),
    ]
