# Generated by Django 2.2.5 on 2021-12-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0006_auto_20211221_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Bard', 'Bard'), ('Ranger', 'Ranger'), ('Fighter', 'Fighter'), ('Warlock', 'Warlock'), ('Cleric', 'Cleric'), ('Barbarian', 'Barbarian'), ('Sorcerer', 'Sorcerer'), ('Wizard', 'Wizard'), ('Druid', 'Driud')], max_length=60),
        ),
    ]
