# Generated by Django 2.2.5 on 2021-12-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0007_auto_20211221_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Druid', 'Driud'), ('Ranger', 'Ranger'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard'), ('Cleric', 'Cleric'), ('Fighter', 'Fighter'), ('Bard', 'Bard'), ('Sorcerer', 'Sorcerer'), ('Barbarian', 'Barbarian')], max_length=60),
        ),
    ]
