# Generated by Django 2.2.5 on 2021-12-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0008_auto_20211221_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Cleric', 'Cleric'), ('Warlock', 'Warlock'), ('Sorcerer', 'Sorcerer'), ('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Fighter', 'Fighter'), ('Ranger', 'Ranger'), ('Druid', 'Driud'), ('Wizard', 'Wizard')], max_length=60),
        ),
    ]
