# Generated by Django 2.2.5 on 2021-12-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0009_auto_20211221_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Sorcerer', 'Sorcerer'), ('Druid', 'Driud'), ('Barbarian', 'Barbarian'), ('Ranger', 'Ranger'), ('Wizard', 'Wizard'), ('Cleric', 'Cleric'), ('Bard', 'Bard'), ('Fighter', 'Fighter'), ('Warlock', 'Warlock')], max_length=60),
        ),
    ]
