# Generated by Django 2.2.5 on 2021-12-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0010_auto_20211221_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Bard', 'Bard'), ('Barbarian', 'Barbarian'), ('Druid', 'Driud'), ('Warlock', 'Warlock'), ('Ranger', 'Ranger'), ('Fighter', 'Fighter'), ('Cleric', 'Cleric'), ('Wizard', 'Wizard'), ('Sorcerer', 'Sorcerer')], max_length=60),
        ),
    ]
