# Generated by Django 2.2.5 on 2021-12-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0014_auto_20211221_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Fighter', 'Fighter'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Wizard', 'Wizard'), ('Druid', 'Driud'), ('Ranger', 'Ranger')], max_length=60),
        ),
    ]
