# Generated by Django 2.2.5 on 2021-12-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNDCharacters', '0015_auto_20211221_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='Character_Class',
            field=models.CharField(choices=[('Sorcerer', 'Sorcerer'), ('Fighter', 'Fighter'), ('Ranger', 'Ranger'), ('Bard', 'Bard'), ('Barbarian', 'Barbarian'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard'), ('Druid', 'Driud'), ('Cleric', 'Cleric')], max_length=60),
        ),
    ]
