# Generated by Django 2.2.5 on 2021-11-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportsCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('Make', models.CharField(blank=True, default='', max_length=60)),
                ('Model', models.CharField(blank=True, default='', max_length=60)),
                ('Engine', models.CharField(blank=True, default='', max_length=60)),
                ('Horsepower', models.DecimalField(decimal_places=0, max_digits=4)),
                ('Top_Speed', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
    ]
