# Generated by Django 2.2.5 on 2022-04-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperCars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercars',
            name='type',
            field=models.CharField(choices=[('McClaren', 'McClaren'), ('Lambo', 'Lambo'), ('Bugatti', 'Bugatti'), ('Ferrari', 'Ferrari')], max_length=60),
        ),
    ]
