# Generated by Django 2.2.5 on 2022-03-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperCars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercars',
            name='type',
            field=models.CharField(choices=[('Ferrari', 'Ferrari'), ('Lambo', 'Lambo'), ('Bugatti', 'Bugatti'), ('McClaren', 'McClaren')], max_length=60),
        ),
    ]
