# Generated by Django 2.2.5 on 2022-04-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperCars', '0002_auto_20220331_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercars',
            name='type',
            field=models.CharField(choices=[('Lambo', 'Lambo'), ('Bugatti', 'Bugatti'), ('Ferrari', 'Ferrari'), ('McClaren', 'McClaren')], max_length=60),
        ),
    ]
