# Generated by Django 2.2.5 on 2022-03-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperCars', '0002_auto_20220328_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercars',
            name='type',
            field=models.CharField(choices=[('Ferrari', 'Ferrari'), ('Bugatti', 'Bugatti'), ('McClaren', 'McClaren'), ('Lambo', 'Lambo')], max_length=60),
        ),
    ]
