# Generated by Django 2.2.5 on 2022-03-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperCars', '0002_auto_20220321_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercars',
            name='type',
            field=models.CharField(choices=[('Ferrari', 'Ferrari'), ('McClaren', 'McClaren'), ('Lambo', 'Lambo'), ('Bugatti', 'Bugatti')], max_length=60),
        ),
    ]
