# Generated by Django 2.2.5 on 2022-03-30 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperCars', '0003_auto_20220329_1953'),
        ('SuperCars', '0003_auto_20220329_2239'),
    ]

    operations = [
    ]
