# Generated by Django 2.2.5 on 2022-04-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperCars', '0004_auto_20220406_0256'),
        ('SuperCars', '0004_auto_20220406_1626'),
    ]

    operations = [
    ]
