# Generated by Django 2.2.5 on 2022-04-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperCars', '0007_auto_20220407_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercars',
            name='type',
            field=models.CharField(choices=[('Bugatti', 'Bugatti'), ('Lambo', 'Lambo'), ('McClaren', 'McClaren'), ('Ferrari', 'Ferrari')], max_length=60),
        ),
    ]
