# Generated by Django 2.2.5 on 2022-04-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperCars', '0008_auto_20220407_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercars',
            name='type',
            field=models.CharField(choices=[('Lambo', 'Lambo'), ('Bugatti', 'Bugatti'), ('McClaren', 'McClaren'), ('Ferrari', 'Ferrari')], max_length=60),
        ),
    ]
