# Generated by Django 2.2.5 on 2022-04-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperCars', '0009_auto_20220407_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercars',
            name='type',
            field=models.CharField(choices=[('McClaren', 'McClaren'), ('Ferrari', 'Ferrari'), ('Bugatti', 'Bugatti'), ('Lambo', 'Lambo')], max_length=60),
        ),
    ]
