# Generated by Django 2.2.5 on 2022-04-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperCars', '0010_auto_20220407_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercars',
            name='type',
            field=models.CharField(choices=[('Lambo', 'Lambo'), ('Ferrari', 'Ferrari'), ('Bugatti', 'Bugatti'), ('McClaren', 'McClaren')], max_length=60),
        ),
    ]
