# Generated by Django 2.2.5 on 2022-04-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperCars', '0015_auto_20220407_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercars',
            name='type',
            field=models.CharField(choices=[('Lambo', 'Lambo'), ('Ferrari', 'Ferrari'), ('McClaren', 'McClaren'), ('Bugatti', 'Bugatti')], max_length=60),
        ),
    ]
