# Generated by Django 2.2.5 on 2022-02-22 23:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0002_auto_20220222_1731'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vehicles',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
