# Generated by Django 2.2.5 on 2021-11-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Snowboarding', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Icons',
            new_name='Ryder',
        ),
    ]
