# Generated by Django 2.2.5 on 2022-05-04 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Age', models.IntegerField(default='')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='gender', max_length=40)),
                ('score', models.FloatField(default=0, max_length=4)),
            ],
            managers=[
                ('Users', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ChooseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicTaste.User')),
            ],
        ),
    ]
