# Generated by Django 2.2.5 on 2022-04-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicTaste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='gender', max_length=40),
        ),
    ]
