# Generated by Django 2.2.5 on 2022-05-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicTaste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='gender', max_length=40),
        ),
    ]
