# Generated by Django 2.2.5 on 2022-05-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicTaste', '0002_auto_20220509_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='gender', max_length=40),
        ),
    ]
