# Generated by Django 2.2.5 on 2022-04-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicTaste', '0003_auto_20220418_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='gender', max_length=40),
        ),
    ]
