# Generated by Django 2.2.5 on 2021-09-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevitFunctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rvtfunction',
            old_name='JOB_CATEGORY',
            new_name='job_category',
        ),
        migrations.RenameField(
            model_name='rvtfunction',
            old_name='REVIT_CATEGORY',
            new_name='revit_category',
        ),
        migrations.RenameField(
            model_name='rvtfunction',
            old_name='REVIT_DESCRIPTION',
            new_name='revit_description',
        ),
        migrations.RenameField(
            model_name='rvtfunction',
            old_name='REVIT_LEVEL',
            new_name='revit_level',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='JOB_CATEGORY',
            new_name='job_category',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='REVIT_LEVEL',
            new_name='revit_level',
        ),
        migrations.RemoveField(
            model_name='rvtfunction',
            name='REVIT_TITLE',
        ),
    ]
