# Generated by Django 2.2.5 on 2021-09-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevitFunctions', '0003_rvtfunction_revit_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvtfunction',
            name='job_category',
            field=models.CharField(choices=[('0 All', '0 All'), ('1 Designer', '1 Designer'), ('2 Production', '2 Production'), ('3 Administration', '3 Administration'), ('4 Project Lead', '4 Project Lead')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(choices=[('0 All', '0 All'), ('1 Designer', '1 Designer'), ('2 Production', '2 Production'), ('3 Administration', '3 Administration'), ('4 Project Lead', '4 Project Lead')], max_length=80),
        ),
    ]
