# Generated by Django 2.2.5 on 2021-10-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevitFunctions', '0004_auto_20210929_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvtfunction',
            name='job_category',
            field=models.CharField(choices=[('0 All', '0 All'), ('1 Designer', '1 Designer'), ('2 Production', '2 Production'), ('3 Designer & Production', '3 Designer & Production'), ('4 Administration', '4 Administration'), ('5 Project Lead', '5 Project Lead')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(choices=[('0 All', '0 All'), ('1 Designer', '1 Designer'), ('2 Production', '2 Production'), ('3 Designer & Production', '3 Designer & Production'), ('4 Administration', '4 Administration'), ('5 Project Lead', '5 Project Lead')], max_length=80),
        ),
    ]
