# Generated by Django 2.2.5 on 2021-10-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevitFunctions', '0005_auto_20211004_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvtfunction',
            name='google_keywords',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
