# Generated by Django 2.2.5 on 2022-03-05 22:34

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('playerWhite', models.CharField(max_length=50)),
                ('playerBlack', models.CharField(max_length=50)),
                ('yearPlayed', models.IntegerField(blank=True)),
                ('PGN', models.TextField(max_length=500)),
                ('winner', models.CharField(max_length=10)),
            ],
            managers=[
                ('Game', django.db.models.manager.Manager()),
            ],
        ),
    ]
