# Generated by Django 2.2.5 on 2022-02-22 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChessOpenings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='fen_string',
        ),
        migrations.AddField(
            model_name='games',
            name='PGN',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='games',
            name='yearPlayed',
            field=models.IntegerField(blank=True),
        ),
    ]
