# Generated by Django 2.2.5 on 2022-01-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('type', models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Herb', 'Herb'), ('Flower', 'Flower'), ('Tree', 'Tree'), ('Shrub', 'Shrub')], max_length=120)),
                ('season_planted', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=120)),
                ('date_planted', models.DateField()),
                ('days_to_harvest', models.IntegerField()),
            ],
        ),
    ]
