# Generated by Django 2.2.5 on 2021-12-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gardening', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='plants',
            managers=[
            ],
        ),
    ]
