# Generated by Django 2.2.5 on 2022-07-26 01:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fbeast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('title', models.CharField(default='Forgotten Beast', max_length=60)),
                ('skin', models.CharField(choices=[('metal', 'metal'), ('meat', 'meat'), ('scale', 'scale'), ('gem', 'gem'), ('fungus', 'fungus')], max_length=60)),
                ('species', models.CharField(choices=[('reptilian', 'reptilian'), ('avian', 'avian'), ('unknown', 'unknown'), ('amphibian', 'amphibian'), ('canine', 'canine'), ('feline', 'feline')], max_length=60)),
                ('power', models.CharField(choices=[('sticky webs', 'sticky webs'), ('deadly dust', 'deadly dust'), ('firey breath', 'firey breath'), ('ominous presence', 'ominous presence'), ('menacing spikes', 'menacing spikes')], max_length=60)),
            ],
            managers=[
                ('Fbeasts', django.db.models.manager.Manager()),
            ],
        ),
    ]
