# Generated by Django 2.2.5 on 2021-11-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dlc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_game', models.CharField(default='', max_length=50)),
                ('dlc_name', models.CharField(default='', max_length=50)),
                ('dlc_key', models.CharField(blank=True, default='', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='', max_length=50)),
                ('genre', models.CharField(choices=[('First Person Shooter', 'First Person Shooter'), ('Real Time Strategy', 'Real Time Strategy'), ('Role Playing Game', 'Role Playing Game'), ('Simulator', 'Simulator'), ('First Person Experience', 'First Person Experience'), ('Action/Adventure', 'Action/Adventure'), ('Massive Multiplayer Online', 'Massive Multiplayer Online'), ('Racing', 'Racing'), ('Sports', 'Sports'), ('Virtual Reality', 'Virtual Reality'), ('Indie Game', 'Indie Game'), ('Builder/Survival', 'Builder/Survival'), ('Open World', 'Open World'), ('Turn Based Tactics', 'Turn Based Tactics')], default='', max_length=50)),
                ('store_name', models.CharField(choices=[('Steam', 'Steam'), ('Epic Games', 'Epic Games'), ('Good Old Games', 'Good Old Games'), ('Battle.net', 'Battle.net'), ('Origin', 'Origin'), ('Oculus', 'Oculus'), ('Uplay', 'Uplay')], default='', max_length=50)),
                ('game_key', models.CharField(blank=True, default='', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(default='', max_length=50)),
                ('genre', models.CharField(choices=[('First Person Shooter', 'First Person Shooter'), ('Real Time Strategy', 'Real Time Strategy'), ('Role Playing Game', 'Role Playing Game'), ('Simulator', 'Simulator'), ('First Person Experience', 'First Person Experience'), ('Action/Adventure', 'Action/Adventure'), ('Massive Multiplayer Online', 'Massive Multiplayer Online'), ('Racing', 'Racing'), ('Sports', 'Sports'), ('Virtual Reality', 'Virtual Reality'), ('Indie Game', 'Indie Game'), ('Builder/Survival', 'Builder/Survival'), ('Open World', 'Open World'), ('Turn Based Tactics', 'Turn Based Tactics')], default='', max_length=50)),
                ('store_name', models.CharField(choices=[('Steam', 'Steam'), ('Epic Games', 'Epic Games'), ('Good Old Games', 'Good Old Games'), ('Battle.net', 'Battle.net'), ('Origin', 'Origin'), ('Oculus', 'Oculus'), ('Uplay', 'Uplay')], default='', max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
