# Generated by Django 2.2.5 on 2021-10-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='genre',
            field=models.CharField(choices=[('Virtual Reality', 'Virtual Reality'), ('Real Time Strategy', 'Real Time Strategy'), ('First Person Experience', 'First Person Experience'), ('First Person Shooter', 'First Person Shooter'), ('Builder/Survival', 'Builder/Survival'), ('Open World', 'Open World'), ('Indie Game', 'Indie Game'), ('Action/Adventure', 'Action/Adventure'), ('Simulator', 'Simulator'), ('Role Playing Game', 'Role Playing Game'), ('Racing', 'Racing'), ('Turn Based Tactics', 'Turn Based Tactics'), ('Sports', 'Sports'), ('Massive Multiplayer Online', 'Massive Multiplayer Online')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='games',
            name='store_name',
            field=models.CharField(choices=[('Oculus', 'Oculus'), ('Epic Games', 'Epic Games'), ('Good Old Games', 'Good Old Games'), ('Steam', 'Steam'), ('Origin', 'Origin'), ('Battle.net', 'Battle.net'), ('Uplay', 'Uplay')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='genre',
            field=models.CharField(choices=[('Virtual Reality', 'Virtual Reality'), ('Real Time Strategy', 'Real Time Strategy'), ('First Person Experience', 'First Person Experience'), ('First Person Shooter', 'First Person Shooter'), ('Builder/Survival', 'Builder/Survival'), ('Open World', 'Open World'), ('Indie Game', 'Indie Game'), ('Action/Adventure', 'Action/Adventure'), ('Simulator', 'Simulator'), ('Role Playing Game', 'Role Playing Game'), ('Racing', 'Racing'), ('Turn Based Tactics', 'Turn Based Tactics'), ('Sports', 'Sports'), ('Massive Multiplayer Online', 'Massive Multiplayer Online')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='store_name',
            field=models.CharField(choices=[('Oculus', 'Oculus'), ('Epic Games', 'Epic Games'), ('Good Old Games', 'Good Old Games'), ('Steam', 'Steam'), ('Origin', 'Origin'), ('Battle.net', 'Battle.net'), ('Uplay', 'Uplay')], default='', max_length=50),
        ),
    ]
