# Generated by Django 2.2.5 on 2021-10-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyMaster', '0003_auto_20211027_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='genre',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Open World', 'Open World'), ('Virtual Reality', 'Virtual Reality'), ('Action/Adventure', 'Action/Adventure'), ('Turn Based Tactics', 'Turn Based Tactics'), ('Simulator', 'Simulator'), ('Massive Multiplayer Online', 'Massive Multiplayer Online'), ('First Person Shooter', 'First Person Shooter'), ('Real Time Strategy', 'Real Time Strategy'), ('Builder/Survival', 'Builder/Survival'), ('First Person Experience', 'First Person Experience'), ('Indie Game', 'Indie Game'), ('Racing', 'Racing'), ('Role Playing Game', 'Role Playing Game')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='games',
            name='store_name',
            field=models.CharField(choices=[('Good Old Games', 'Good Old Games'), ('Steam', 'Steam'), ('Uplay', 'Uplay'), ('Oculus', 'Oculus'), ('Epic Games', 'Epic Games'), ('Battle.net', 'Battle.net'), ('Origin', 'Origin')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='genre',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Open World', 'Open World'), ('Virtual Reality', 'Virtual Reality'), ('Action/Adventure', 'Action/Adventure'), ('Turn Based Tactics', 'Turn Based Tactics'), ('Simulator', 'Simulator'), ('Massive Multiplayer Online', 'Massive Multiplayer Online'), ('First Person Shooter', 'First Person Shooter'), ('Real Time Strategy', 'Real Time Strategy'), ('Builder/Survival', 'Builder/Survival'), ('First Person Experience', 'First Person Experience'), ('Indie Game', 'Indie Game'), ('Racing', 'Racing'), ('Role Playing Game', 'Role Playing Game')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='store_name',
            field=models.CharField(choices=[('Good Old Games', 'Good Old Games'), ('Steam', 'Steam'), ('Uplay', 'Uplay'), ('Oculus', 'Oculus'), ('Epic Games', 'Epic Games'), ('Battle.net', 'Battle.net'), ('Origin', 'Origin')], default='', max_length=50),
        ),
    ]
