# Generated by Django 2.2.5 on 2021-10-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyMaster', '0004_auto_20211027_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='genre',
            field=models.CharField(choices=[('First Person Shooter', 'First Person Shooter'), ('Real Time Strategy', 'Real Time Strategy'), ('Role Playing Game', 'Role Playing Game'), ('Simulator', 'Simulator'), ('First Person Experience', 'First Person Experience'), ('Action/Adventure', 'Action/Adventure'), ('Massive Multiplayer Online', 'Massive Multiplayer Online'), ('Racing', 'Racing'), ('Sports', 'Sports'), ('Virtual Reality', 'Virtual Reality'), ('Indie Game', 'Indie Game'), ('Builder/Survival', 'Builder/Survival'), ('Open World', 'Open World'), ('Turn Based Tactics', 'Turn Based Tactics')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='games',
            name='store_name',
            field=models.CharField(choices=[('Steam', 'Steam'), ('Epic Games', 'Epic Games'), ('Good Old Games', 'Good Old Games'), ('Battle.net', 'Battle.net'), ('Origin', 'Origin'), ('Oculus', 'Oculus'), ('Uplay', 'Uplay')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='genre',
            field=models.CharField(choices=[('First Person Shooter', 'First Person Shooter'), ('Real Time Strategy', 'Real Time Strategy'), ('Role Playing Game', 'Role Playing Game'), ('Simulator', 'Simulator'), ('First Person Experience', 'First Person Experience'), ('Action/Adventure', 'Action/Adventure'), ('Massive Multiplayer Online', 'Massive Multiplayer Online'), ('Racing', 'Racing'), ('Sports', 'Sports'), ('Virtual Reality', 'Virtual Reality'), ('Indie Game', 'Indie Game'), ('Builder/Survival', 'Builder/Survival'), ('Open World', 'Open World'), ('Turn Based Tactics', 'Turn Based Tactics')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='store_name',
            field=models.CharField(choices=[('Steam', 'Steam'), ('Epic Games', 'Epic Games'), ('Good Old Games', 'Good Old Games'), ('Battle.net', 'Battle.net'), ('Origin', 'Origin'), ('Oculus', 'Oculus'), ('Uplay', 'Uplay')], default='', max_length=50),
        ),
    ]
