# Generated by Django 2.2.5 on 2021-10-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyMaster', '0006_auto_20211029_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
