# Generated by Django 2.2.5 on 2022-05-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='first', max_length=25)),
                ('last_name', models.CharField(blank=True, default='last', max_length=25)),
                ('email', models.EmailField(blank=True, default='email', max_length=25)),
                ('phone', models.CharField(blank=True, default='optional', max_length=15)),
                ('travelDate', models.DateField()),
                ('accommodation', models.CharField(choices=[('Coach Seat', 'Coach Seat'), ('Roomette', 'Roomette'), ('Bedroom', 'Bedroom'), ('Bedroom Suite', 'Bedroom Suite'), ('Family Bedroom', 'Family Bedroom'), ('Accessible Bedroom', 'Accessible Bedroom')], default='', max_length=20)),
                ('guests', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
