# Generated by Django 2.2.5 on 2021-10-15 04:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_lvl', models.IntegerField()),
                ('item_type', models.CharField(max_length=2)),
                ('item_expac', models.CharField(max_length=50)),
            ],
            managers=[
                ('Items', django.db.models.manager.Manager()),
            ],
        ),
    ]
