# Generated by Django 2.2.5 on 2021-10-18 17:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('MATERIALS', 'Materials'), ('TOOLS', 'Tools'), ('WEAPONS', 'Weapons'), ('ARMOR', 'Armor')], max_length=20)),
                ('item_name', models.CharField(max_length=50)),
                ('item_level', models.IntegerField()),
                ('item_description', models.TextField(default='Item Description', max_length=1000)),
            ],
            managers=[
                ('Items', django.db.models.manager.Manager()),
            ],
        ),
    ]
