# Generated by Django 2.2.5 on 2021-10-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ValItems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_expac',
        ),
        migrations.AddField(
            model_name='item',
            name='item_desc',
            field=models.TextField(default='Item Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(
                choices=[('MATERIALS', 'Materials'), ('TOOLS', 'Tools'), ('WEAPONS', 'Weapons'), ('ARMOR', 'Armor')],
                max_length=20),
        ),
    ]
