# Generated by Django 2.2.5 on 2021-10-16 03:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ValItems', '0002_auto_20211015_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_desc',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_lvl',
            new_name='item_level',
        ),
    ]
