# Generated by Django 2.2.5 on 2021-10-17 05:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ('ValItems', '0003_auto_20211015_2044'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('item_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(
                choices=[('Materials', 'Materials'), ('Tools', 'Tools'), ('Weapons', 'Weapons'), ('Armor', 'Armor')],
                max_length=20),
        ),
    ]
