# Generated by Django 2.2.5 on 2021-10-18 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=30)),
                ('vendor_number', models.IntegerField()),
                ('vendor_category', models.CharField(choices=[('Other', 'Other'), ('Produce', 'Produce'), ('Tobacco', 'Tobacco'), ('Vehicle', 'Vehicle')], default=0, max_length=60)),
                ('vendor_contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_pn', models.IntegerField()),
                ('item_name', models.CharField(max_length=30)),
                ('item_count', models.IntegerField()),
                ('item_category', models.CharField(choices=[('Other', 'Other'), ('Produce', 'Produce'), ('Tobacco', 'Tobacco'), ('Vehicle', 'Vehicle')], max_length=60)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('item_vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CoreItemManagement.Vendor')),
            ],
        ),
    ]
