# Generated by Django 2.2.5 on 2021-10-15 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_name', models.CharField(max_length=30)),
                ('_count', models.IntegerField()),
                ('category', models.CharField(choices=[('Other', 'Other'), ('Tobacco', 'Tobacco'), ('Vehicle', 'Vehicle'), ('Produce', 'Produce')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_pn', models.IntegerField()),
                ('item_name', models.CharField(max_length=30)),
                ('item_count', models.IntegerField()),
                ('item_category', models.CharField(choices=[('Other', 'Other'), ('Tobacco', 'Tobacco'), ('Vehicle', 'Vehicle'), ('Produce', 'Produce')], max_length=60)),
                ('item_price', models.IntegerField()),
                ('item_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreItemManagement.Vendor')),
            ],
        ),
    ]
