# Generated by Django 2.2.5 on 2021-10-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreItemManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('Tobacco', 'Tobacco'), ('Vehicle', 'Vehicle'), ('Produce', 'Produce'), ('Other', 'Other')], max_length=60),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('Tobacco', 'Tobacco'), ('Vehicle', 'Vehicle'), ('Produce', 'Produce'), ('Other', 'Other')], max_length=60),
        ),
    ]
