# Generated by Django 2.2.5 on 2021-10-15 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreItemManagement', '0002_auto_20211015_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='_name',
            new_name='vendor_name',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='_count',
            new_name='vendor_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='category',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_category',
            field=models.CharField(choices=[('Vehicle', 'Vehicle'), ('Other', 'Other'), ('Produce', 'Produce'), ('Tobacco', 'Tobacco')], default=0, max_length=60),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('Vehicle', 'Vehicle'), ('Other', 'Other'), ('Produce', 'Produce'), ('Tobacco', 'Tobacco')], max_length=60),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_vendor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CoreItemManagement.Vendor'),
        ),
    ]
