# Generated by Django 2.2.5 on 2021-10-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreItemManagement', '0003_auto_20211015_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('Other', 'Other'), ('Produce', 'Produce'), ('Tobacco', 'Tobacco'), ('Vehicle', 'Vehicle')], max_length=60),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_category',
            field=models.CharField(choices=[('Other', 'Other'), ('Produce', 'Produce'), ('Tobacco', 'Tobacco'), ('Vehicle', 'Vehicle')], default=0, max_length=60),
        ),
    ]
