# Generated by Django 2.2.5 on 2022-05-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TexMex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('beverages', 'beverages'), ('appetizers', 'appetizers'), ('entrees', 'entrees'), ('desserts', 'desserts'), ('soups', 'soups')], max_length=12),
        ),
    ]
