# Generated by Django 2.2.5 on 2022-06-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TexMex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('appetizers', 'appetizers'), ('soups', 'soups'), ('entrees', 'entrees'), ('beverages', 'beverages'), ('desserts', 'desserts')], max_length=12),
        ),
    ]
