# Generated by Django 2.2.5 on 2022-05-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TexMex', '0002_auto_20220518_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('beverages', 'beverages'), ('soups', 'soups'), ('entrees', 'entrees'), ('desserts', 'desserts'), ('appetizers', 'appetizers')], max_length=12),
        ),
    ]
