# Generated by Django 2.2.5 on 2021-04-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarReviewsApp', '0004_auto_20210416_1153'),
        ('GuitarReviewsApp', '0004_auto_20210420_1643'),
    ]

    operations = [
    ]
