# Generated by Django 2.2.5 on 2021-06-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_songs',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='ArtistTrack.Song'),
        ),
    ]
