# Generated by Django 2.2.5 on 2021-06-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistTrack', '0002_auto_20210601_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_songs',
            field=models.ManyToManyField(blank=True, default=None, to='ArtistTrack.Song'),
        ),
    ]
