# Generated by Django 2.2.5 on 2021-06-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistTrack', '0003_auto_20210601_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_songs',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtistTrack.Playlist'),
        ),
    ]
