# Generated by Django 2.2.5 on 2021-06-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistTrack', '0004_auto_20210601_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
