# Generated by Django 2.2.5 on 2021-06-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistTrack', '0006_auto_20210601_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
