# Generated by Django 2.2.5 on 2021-06-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistTrack', '0007_auto_20210601_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.IntegerField(),
        ),
    ]
