# Generated by Django 2.2.5 on 2021-06-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistTrack', '0009_auto_20210601_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
