# Generated by Django 2.2.5 on 2021-06-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistTrack', '0010_auto_20210601_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('nu-metal', 'nu-metal'), ('metalcore', 'metalcore'), ('death metal', 'death metal'), ('rock', 'rock'), ('pop', 'pop'), ('classical', 'classical'), ('other', 'other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
