# Generated by Django 2.2.5 on 2021-10-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OregonRocks', '0002_editrockloc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditRockLoc',
        ),
    ]
