# Generated by Django 2.2.5 on 2021-10-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UtadaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='songs',
            field=models.CharField(choices=[('Kiss & Cry', 'Beautiful World'), ('Flavor of Life (Ballad Version)', 'Sakura Drops'), ('Simple & Clean', 'Sanctuary'), ('Keep Trying', 'Automatic'), ('Hikari', 'Passion')], max_length=500),
        ),
    ]
