# Generated by Django 2.2.5 on 2021-11-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UtadaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='songs',
            field=models.CharField(max_length=500),
        ),
    ]
