# Generated by Django 2.2.5 on 2022-05-03 04:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('pg', 'Point Guard'), ('sg', 'Shooting Guard'), ('sf', 'Small Forward'), ('pf', 'Power Forward'), ('c', 'Center')], default='Point Guard', max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('points', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('rebounds', models.PositiveIntegerField()),
                ('steals', models.PositiveIntegerField()),
                ('blocks', models.PositiveIntegerField()),
                ('turnovers', models.PositiveIntegerField()),
            ],
            managers=[
                ('games', django.db.models.manager.Manager()),
            ],
        ),
    ]
