# Generated by Django 2.2.5 on 2022-06-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
                ('company', models.CharField(default='', max_length=30)),
                ('stack', models.CharField(choices=[('Back-End', 'Back-End'), ('Unknown', 'Unknown'), ('Full-Stack', 'Full-Stack'), ('Front-End', 'Front-End')], max_length=15)),
                ('startup', models.CharField(choices=[('Unknown', 'Unknown'), ('No', 'No'), ('Yes', 'Yes')], max_length=8)),
                ('location', models.CharField(max_length=30)),
                ('exp_required', models.CharField(max_length=30)),
                ('minimum_pay', models.CharField(max_length=30)),
                ('maximum_pay', models.CharField(max_length=30)),
                ('date_added', models.DateField()),
                ('job_url', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
                ('company', models.CharField(default='', max_length=30)),
                ('minimum_pay', models.CharField(max_length=30)),
                ('maximum_pay', models.CharField(max_length=30)),
                ('date_added', models.DateField()),
                ('job_url', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
