# Generated by Django 2.2.5 on 2022-03-10 19:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seasons_played', models.IntegerField(default='')),
                ('mvp_awards', models.IntegerField(default='')),
                ('championships', models.IntegerField(default='')),
            ],
            managers=[
                ('Player', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('conference', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=15)),
            ],
            managers=[
                ('Team', django.db.models.manager.Manager()),
            ],
        ),
    ]
